- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/ci/default-values.yaml
- charts/jenkins/templates/jcasc-config.yaml
This avoids rendering empty config maps in case no values is provides.
With this one can simply disable rendering authorizationStrategy and
securityRealm if their configuration is provided outside of the chart.
```yaml
master
JCasC:
configScripts:
authorizationStrategy: ""
securityRealm: ""
```
Signed-off-by: Torsten Walter <mail@torstenwalter.de>
> Do not render empty JCasC templates

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/README.md
Update chart to apiiVersion v2, which means it no longer supports helm version 2, but only version 3.
> Migrate to Helm 3 - apiVersion is now v2

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/jenkins-master-secondary-ingress.yaml
- charts/jenkins/values.yaml
- fixes #44 - Allow a secondary ingress for making webbooks public
> Add secondary ingress

- charts/jenkins/VALUES_SUMMARY.md
- charts/jenkins/templates/deprecation.yaml
- charts/jenkins/templates/jenkins-master-statefulset.yaml
- charts/jenkins/values.yaml
Signed-off-by: Dylan Piergies <dylan.piergies@gmail.com>
> Replace Deployment with StatefulSet

- .github/ISSUE_TEMPLATE/bug_report.md
- README.md
- charts/jenkins/Chart.yaml
- charts/jenkins/README.md
This name is up to the final user after all, so better we use a more convenient suggestion. Jenkins Docker Hub repo was moved from `jenkinsci` to `jenkins` for example.
> Change Helm repo name from jenkinsci to jenkins

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/values.yaml
Bump configuration-as-code-plugin to 1.43
https://github.com/jenkinsci/configuration-as-code-plugin/issues/1478
Have a nice day 💯
> Bumped casc version to 1.43

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/jenkins-backup-cronjob.yaml
- charts/jenkins/templates/jenkins-master-deployment.yaml
- charts/jenkins/values.yaml
To comply with CIS kubernetes benchmark, PodSecurityPolicies should require that at least NET_RAW, preferrably ALL 
capabilities be dropped. In order to run Jenkins under such a PodSecurityPolicy, it must be possible to configure the capabilities of the jenkins deployment.
Signed-off-by: Tor Ake Fransson <tor-ake.fransson@linefeed.se>
- fixes #
> * Add option to configure securityContext capabilities

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES_SUMMARY.md
- charts/jenkins/ci/test-values.yaml
- charts/jenkins/templates/_helpers.tpl
- charts/jenkins/tests/jcasc-config-test.yaml
- charts/jenkins/values.yaml
This PR adds the option to set annotations for the pod template from the helm chart.
> Add option for setting annotations to the pod template

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/README.md
- charts/jenkins/templates/jenkins-master-ingress.yaml
- charts/jenkins/tests/jenkins-master-ingress-test.yaml
This PR fixes the need for specifying `master.ingress.paths` even if no paths need to be overwritten.
This is done by adding an additional check to see if  `master.ingress.paths` is even defined before taking the length
> Fix error on missing `ingress.paths` value

- .github/workflows/release.yaml
Locations of `stable` and `incubator` repositories in the release action are no longer valid and the step `Add dependency chart repos` fails when adding them
```
Error: repo "https://kubernetes-charts.storage.googleapis.com/" is no longer available; try "https://charts.helm.sh/stable" instead
```
For that reason there is *no* new release after each merge to the `main` branch
> Updated locations of stable and incubator Helm repositories

- .github/workflows/release.yaml
This updates helm version to 3.4.0 and uses `fetch-depth` to checkout history.
Not sure if this already fixes the release pipeline or not, so let's see what happens with this.
- Part-of: #126
> use helm 3.4.0 for release pipeline

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/config.yaml
- charts/jenkins/tests/config-test.yaml
- charts/jenkins/tests/jenkins-master-deployment-test.yaml
Updates the helm chart to use the plugin-installation-manager-tool
I've created a PR to add the new version to the docker images, so it'll soon be working.
Note: before 2.1.1 it tries to delete the entire directory where plugins are installed into, which breaks in the helm chart because its a volume - Fixed in https://github.com/jenkinsci/plugin-installation-manager-tool/pull/215
Added a version check and added https://github.com/jenkinsci/docker/pull/1015 so it gets released in new docker images
I don't know how to run the tests though
> Use plugin-installation-manager-tool

- .github/workflows/lint-test.yaml
- ct.yaml
https://github.com/helm/chart-testing-action/releases/tag/v2.0.0 is releases. It provides native support to run additional commands as it installs `ct` binary locally. 
With this we switch back to an "officially" maintained GitHub action.
- fixes #
It backports #122 into main.
> CI: Use chart-testing-action 2.0.0

- .github/workflows/lint-test.yaml
Looks like 0.2.5 broke something.
With the newer version the tests fail.
- fixes #
> pin helm unittest to 0.2.4

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/jenkins-master-deployment.yaml
- charts/jenkins/tests/jenkins-master-deployment-test.yaml
Signed-off-by: janssk1 <janssk1@hotmail.com>
Don't use a volume for /tmp. It causes issues on certain KS environments
- fixes #135 
Was able to install jenkins and run jmap. Not sure if any other feature requires all containers in the pod to point to the same /tmp folder. 
- [ x] [DCO](https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ x] Chart Version bumped
- [ x] CHANGELOG.md was updated
> Dropping /tmp volume

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/jenkins-master-deployment.yaml
- charts/jenkins/tests/jenkins-master-deployment-test.yaml
Fix issues with quoted values like : `-Dhudson.model.DirectoryBrowserSupport.CSP="default-src 'self';"`
> fix: java_ops issue with quoted values

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/README.md
- charts/jenkins/templates/config.yaml
- charts/jenkins/tests/config-test.yaml
- charts/jenkins/tests/jcasc-config-test.yaml
- charts/jenkins/tests/jenkins-master-deployment-test.yaml
- charts/jenkins/values.yaml
- Use lts version 2.249.3
- Update kubernetes, workflow-aggregator, git and configuration-as-code plugins.
- remove plugins which are provided as dependency
- Fail apply_config.sh script if an error occurs.
- fixes #140
> Update configured plugins

- charts/jenkins/CHANGELOG.md
- charts/jenkins/README.md
- charts/jenkins/VALUES_SUMMARY.md
- charts/jenkins/templates/NOTES.txt
- charts/jenkins/templates/_helpers.tpl
- charts/jenkins/templates/deprecation.yaml
- charts/jenkins/templates/jenkins-controller-statefulset.yaml
- charts/jenkins/templates/secret.yaml
- charts/jenkins/tests/jcasc-config-test.yaml
- charts/jenkins/tests/jenkins-controller-statefulset-test.yaml
- charts/jenkins/tests/secret-test.yaml
- charts/jenkins/values.yaml
configure admin user via JCasC
- admin username and password are no longer exposed as environment
variables
- admin password is not modified on helm updates instead the values from
the existing secret is re-used
- default legth of admin password was increased
- renamed useSecurity to adminSecret
- fixes #20
- fixes #94
> Configure admin user via configuration as code

- charts/jenkins/CHANGELOG.md
- charts/jenkins/templates/tests/jenkins-test.yaml
The referenced image `dduportal/bats:0.4.0` has been updated 4 years ago and is still using [docker image manifest v1](https://github.com/moby/moby/blob/master/image/spec/v1.md) which has [been deprecated](https://docs.docker.com/registry/spec/deprecated-schema-v1/).
Current versions [1.1.0](https://github.com/dduportal-dockerfiles/bats/releases/tag/1.1.0) do not have any shell installed and thus can not be used to copy `bats` into the test image.
This is why I have updated the image from `dduportal/bats:0.4.0` to the official `bats/bats:1.2.1` image from [https://hub.docker.com/r/bats/bats](https://hub.docker.com/r/bats/bats).
More information on the v1 deprecation which affected us after implementing our own Docker image cache:
* …
> Updated UI tests to use official BATS image

- charts/jenkins/templates/deprecation.yaml
Users would want a hint if they are using a value, which is no longer supported.
> Check usage of deprecated imageTag

- charts/jenkins/templates/_helpers.tpl
- charts/jenkins/templates/home-pvc.yaml
- charts/jenkins/templates/jcasc-config.yaml
- charts/jenkins/templates/jenkins-agent-svc.yaml
- charts/jenkins/templates/jenkins-backup-cronjob.yaml
- charts/jenkins/templates/jenkins-backup-rbac.yaml
- charts/jenkins/templates/jenkins-controller-alerting-rules.yaml
- charts/jenkins/templates/jenkins-controller-backendconfig.yaml
- charts/jenkins/templates/jenkins-controller-ingress.yaml
- charts/jenkins/templates/jenkins-controller-networkpolicy.yaml
- charts/jenkins/templates/jenkins-controller-route.yaml
- charts/jenkins/templates/jenkins-controller-secondary-ingress.yaml
- charts/jenkins/templates/jenkins-controller-servicemonitor.yaml
- charts/jenkins/templates/jenkins-controller-statefulset.yaml
- charts/jenkins/templates/jenkins-controller-svc.yaml
- charts/jenkins/templates/rbac.yaml
- charts/jenkins/templates/secret-https-jks.yaml
- charts/jenkins/templates/secret.yaml
- charts/jenkins/templates/service-account-agent.yaml
- charts/jenkins/templates/service-account.yaml
Before:
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
name: RELEASE-NAME-jenkins
namespace: cockpit
labels:
"app.kubernetes.io/name": 'jenkins'
"app.kubernetes.io/managed-by": "Helm"
"app.kubernetes.io/instance": "RELEASE-NAME"
"app.kubernetes.io/component": "jenkins-controller"
```
After:
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
name: RELEASE-NAME-jenkins
namespace: cockpit
labels:
"app.kubernetes.io/name": 'jenkins'
"app.kubernetes.io/managed-by": "Helm"
"app.kubernetes.io/instance": "RELEASE-NAME"
"app.kubernetes.io/component": "jenkins-controller"
```
- fixes #
I played quite a bit with include, but getting white spaces right was a …
> Remove whitespace when not rendering helm.sh/chart label

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/jenkins-backup-cronjob.yaml
There is an error when the backup is enabled. This PR fixes it.
**The workaround** 
set `.Values.master.tolerations`, `.Values.master.nodeSelector` and `.Values.checkDeprecation` variable
`master`->`controller` replacement  was not complete in charts/jenkins/templates/jenkins-backup-cronjob.yaml
> Fix variable names

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/README.md
Realized I had an error in #180, specifically regarding the format of `persistence.mounts` for mounting additional secrets to the controller. This is how it should look instead.
@torstenwalter apologies for the mix-up.
> fix error in additional secrets documentation

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
Update appVersion since current LTS version of Jenkins is v2.263.1
Mismatch between appVersion and the actual version used.
I hope you are all doing relatively well during this challenging year.
> Update appVersion to match current LTS version of Jenkins

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/tests/jenkins-controller-statefulset-test.yaml
- charts/jenkins/values.yaml
If we specify an app version in the chart then we should also set the image to that version.
(That's something I forgot when making that change).
- fixes #
> Use 2.263.1 as image version (latest LTS)

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/jenkins-controller-ingress.yaml
- charts/jenkins/templates/jenkins-controller-secondary-ingress.yaml
- charts/jenkins/values.yaml
When deploying this chart in a 1.19 cluster or above we get:
```
W1217 09:08:00.259566   14276 warnings.go:67] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
```
- fixes #
> use networking.k8s.io/v1 for ingress when k8s >= 1.19

- .github/stale.yml
Let's wait for 60 days before issues are marked as stale and another 21 days before issues are closed.
- fixes #
> stale bot: increase time before acting on issues

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/README.md
- charts/jenkins/VALUES_SUMMARY.md
This PR fix some parts of the chart documentation to help newcomers around JCasC configuration:
- Add an explicit requirement about the mandatory plugins required by the chart
- Improve the JCasC configuration explanation for newcomers
- Fix the documented default value for the directive `controller.installPlugins`
- N/A.
🎅 Merry Christmas and Happy New Year!
> Improve Documentation around JCasc and Custom Image

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES_SUMMARY.md
- charts/jenkins/templates/jenkins-backup-cronjob.yaml
- charts/jenkins/values.yaml
With full usage of JCasC, there is often no need to backup the full Jenkins instance. The only thing needing backup are the job logs and artifacts (so the /job folder). 
This enables much faster backups, since the backup is a lot smaller. In my testing I was able to cut down the backup time from 3-4 hours to only a few minutes.
With this pull request the user can select "onlyJobs=true" and have only the jenkins_home/jobs folder backed up.
If you have better idea how to implement this, please let me know. :)
> Enable to only backup job folder

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/README.md
- charts/jenkins/VALUES_SUMMARY.md
- charts/jenkins/templates/jenkins-backup-cronjob.yaml
- charts/jenkins/templates/jenkins-controller-statefulset.yaml
- charts/jenkins/tests/jenkins-backup-cronjob-test.yaml
- charts/jenkins/tests/jenkins-controller-statefulset-test.yaml
- charts/jenkins/values.yaml
This PR introduces the `podSecurityContextOverride` value that completely overwrites `securityContext` in both the controller `StatefulSet` and backup `CronJob`.  It gives greater flexability in what can be put in the pod `securityContext` block, not limited to just `runAsUse`, `fsGroup`, and `securityContextCapabilities`.
In our particular case, we need to be able to unset `fsGroup` and set `supplementalGroups` instead.  Using an override as implemented, would allow use of other `securityContext` values without further complicating the existing Helm Chart.
This is related to the solution in [ kubernetes/kubernetes - Timeout expired waiting for volumes to attach #67014](https://github.com/kubernetes/kubernetes/issues/67014).
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, …
> Adding podSecurityContextOverride

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/tests/jenkins-controller-statefulset-test.yaml
- charts/jenkins/values.yaml
Signed-off-by: Gareth Evans <gareth@bryncynfelin.co.uk>
2.263.2 is a security release.
> chore(deps): bump jenkins version from 2.263.1 to 2.263.2

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/tests/jenkins-controller-statefulset-test.yaml
- charts/jenkins/values.yaml
Signed-off-by: Gareth Evans <gareth@bryncynfelin.co.uk>
2.263.3 is a security release.
> chore(deps): bump jenkins version from 2.263.2 to 2.263.3

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES_SUMMARY.md
- charts/jenkins/tests/config-test.yaml
- charts/jenkins/tests/jenkins-controller-statefulset-test.yaml
- charts/jenkins/values.yaml
This PR is upgrading the Git plugin from v4.4.5 to v4.5.2. Without this change, the BlueOcean plugin in the latest version fails to install and requires to override all plugins in `controller.installPlugins`.
> Updating git plugin version

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/jenkins-controller-statefulset.yaml
Signed-off-by: James Fogarty <jayfo@users.noreply.github.com>
Applies `namespaceOverride` to sidecar that loads JCasC.
Fixes #237
> Apply namespaceOverride when loading JCasC

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES_SUMMARY.md
- charts/jenkins/templates/jenkins-agent-svc.yaml
- charts/jenkins/tests/jenkins-agent-svc-test.yaml
- charts/jenkins/values.yaml
Need to expose the agent listener port to add external agents via JNLP (e.g.: using the swarm plugin).
There is a bug now, when specifying the agentListenerServiceType to NodePort, is will automatically assign the agentListenerPort to the nodePort value of the service. This results in a kubernetes exception as the default port 50000 from agentListenerPort is out of range of the default NodePort range of kubernetes (30000-32767).
I added an optional value controller.agentListenerNodePort that allows to set a node port of generate a random one by Kubernetes if not specified.
- fixes #
> Fixing bug when setting agentListenerServiceType to NodePort

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES_SUMMARY.md
- charts/jenkins/templates/jenkins-controller-statefulset.yaml
- charts/jenkins/tests/jenkins-controller-statefulset-test.yaml
- charts/jenkins/values.yaml
Add an option controller.updateStrategy to set the spec.updateStrategy for StatefulSet.
- fixes #191
- [ x] [DCO](https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ x] Chart Version bumped
- [ x] CHANGELOG.md was updated
> Adding controller.updateStrategy (#191)

- .github/workflows/sync-lts.yaml
Signed-off-by: Gareth Evans <gareth@bryncynfelin.co.uk>
Tries to determine if an update is available before making changes to files, this is an attempt to stop empty PRs from being created.
Also, enabled the workflow_dispatch event type so this can be manually triggered if required.
> fix: only create update and PR if an update is available

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES_SUMMARY.md
- charts/jenkins/values.yaml
- The current documentation is not describing the correct values for the Kubernetes probes (wrong keys, missing keys, and false default values)
- If a user is running on a Kubernetes cluster <= 1.18, then startup probes might not be available and the initialDelay should be documented to holds off the liveness probe, to avoid a premature restart of Jenkins triggered by the local Kubelet.
N.A.
> Fix documentation for the kubernetes probes

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/_helpers.tpl
- charts/jenkins/tests/jcasc-config-test.yaml
Fixes https://github.com/jenkinsci/helm-charts/issues/270. Calculate consistent unique agent IDs to be used in pod templates
> Calculate consistent unique agent IDs to be used in pod templates

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/jenkins-controller-ingress.yaml
- charts/jenkins/tests/jenkins-controller-ingress-test.yaml
Fixes rendering `controller.ingress.path` options. It does not make sense to put it under the branch of when `paths` are explicitly defined, it should be in the block where `paths` are empty.
> Fix rendering of controller.ingress.path

- .github/workflows/sync-lts.yaml
- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
Was mentioned on IRC:
<halkeye[m]> dev.g4v:halkeye 
timja: btw, we should claim artifacthub repo ownership, and adding the artifacthub annotations - https://artifacthub.io/packages/helm/halkeye/wallabag  - changelog and docker image security scans
11:38 PM 
(i'll do it eventually, just super distracted right now)
> Add images metadata for artifacthub

- .github/workflows/sync-lts.yaml
- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES_SUMMARY.md
- charts/jenkins/tests/jenkins-controller-statefulset-test.yaml
- charts/jenkins/values.yaml
Changes the default image to jdk11, this follows on from changing the official docs to use jdk11 images everywhere and is a gradual move away from Java 8.
I'm not sure if this fits into a semver minor, happy to move it to a major just let me know
- fixes #
> Change default image to jdk11 variant

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES_SUMMARY.md
- charts/jenkins/templates/config.yaml
- charts/jenkins/tests/config-test.yaml
- charts/jenkins/tests/jenkins-controller-statefulset-test.yaml
- charts/jenkins/values.yaml
Configure the plugin-installation-manager-tool to skip latest when the whole list of plugins have been defined with the installPlugins.
This should help to bump the version of all the plugins when upgrading the helm.
For instance, if bumping a version of an explicit plugin, then `helm upgrade`, if any of the other explicit plugins have been released with a new version, the init container will fail if all plugins were not bumped. 
It adds the latest flag -> https://github.com/jenkinsci/plugin-installation-manager-tool#cli-options
- https://github.com/jenkinsci/plugin-installation-manager-tool/issues/318
> Enable --latest flag for the jenkins-plugin-cli in the init container

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES_SUMMARY.md
- charts/jenkins/templates/jenkins-agent-svc.yaml
- charts/jenkins/tests/jenkins-agent-svc-test.yaml
- charts/jenkins/values.yaml
This can be useful in cases where all agents are using Websocket
connections via the primary HTTP(s) service.
Defaulted new parameter to `true` in `values.yaml` to maintain existing
behaviour.
Added parameter to `VALUES_SUMMARY.md`.
Also added a test to verify that the service doesn't get created when
setting `controller.agentListenerEnabled` to `false`.
> Add suppot for disabling the Agent listener service.

- .github/workflows/sync-lts.yaml
- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/README.md
- charts/jenkins/VALUES_SUMMARY.md
- charts/jenkins/templates/jenkins-controller-statefulset.yaml
- charts/jenkins/tests/secret-existing-test.yaml
- charts/jenkins/values.yaml
@maorfr @torstenwalter @mogaal 
adds the ability to mount existing secrets to use with [kubernetes secrets jcasc](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/secrets.adoc#kubernetes-secrets)
- fixes #334(, fixes #334)
the [Additional Secrets](https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins#additional-secrets) feature by itself does not resolve the issue of providing sensitive info to the chart.  
since the `value` key expects a sensitive secret, it cannot commit to git, thus the problem moved from `JCasC` property to `additionalSecrets`.
this feature aims to resolve the issue above.
> feat(jcasc): add additionalExistingSecrets capability

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/README.md
the documentation recommends setting `installPlugins` to an empty list, but that doesn't work
```
$ helm template jenkins/jenkins --set controller.installPlugins=[] -s templates/config.yaml
Error: template: jenkins/templates/jenkins-controller-statefulset.yaml:47:28: executing "jenkins/templates/jenkins-controller-statefulset.yaml" at <include (print $.Template.BasePath "/config.yaml") .>: error calling include: template: jenkins/templates/config.yaml:71:37: executing "jenkins/templates/config.yaml" at <.Values.controller.installPlugins>: range can't iterate over []
```
Originally we had set it to null to clear it out, which worked:
```
$ helm template jenkins/jenkins --set controller.installPlugins= -s templates/config.yaml
```
But we're deploying it through kustomize and today our …
> Correct documentation for disabling plugin download

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/jenkins-controller-statefulset.yaml
Removes quotes from keystore file path. I've tested it by deploying Jenkins with these local changes, and Jenkins starts without a stacktrace
- fixes #364
> Fix #364 httpsKeyStore file quoting issue

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/README.md
- charts/jenkins/VALUES_SUMMARY.md
- charts/jenkins/templates/secret-claims.yaml
- charts/jenkins/tests/secret-claims-test.yaml
- charts/jenkins/values.yaml
This commit adds support for generating `SecretClaim` resources which
can be used to automatically create Kubernetes secrets from HashiCorp
Vault via `kube-vault-controller`.
Tests added.
Changelog updated and version bumped.
README.md and VALUES_SUMMARY.md updated.
Signed-off-by: Gavin Williams <fatmcgav@gmail.com>
> feat: Add support for `SecretClaim` resources

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/jenkins-controller-statefulset.yaml
- charts/jenkins/tests/jenkins-controller-statefulset-test.yaml
- charts/jenkins/values.yaml
The current way cli arguments are passed to the WAR is quite opinionated and only supports HTTP & HTTPS options. This change allows a user to override them and specify anything with `overrideArgs`.
I need this to pass `--requestHeaderSize=32768` to the WAR but there are many other arguments that could be supplied https://www.jenkins.io/doc/book/installing/initial-settings/
Example usage:
```
controller:
overrideArgs:
- --httpPort=8080
- --requestHeaderSize=32768
```
Signed-off-by: David Sayers <david@sayers.it>
> Override WAR Arguments

- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES_SUMMARY.md
- charts/jenkins/templates/_helpers.tpl
- charts/jenkins/values.yaml
Signed-off-by: Tomasz Woźniak <tomlee@cybertronika.eu>
Add variable to set name of default cloud. Default it is "kubernetes" and you have possibility to change it.
> Add variable to set name of default cloud name in Jenkins configuration

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/jenkins-controller-statefulset.yaml
Allows a java keystore containing CA certificate to be mounted in init container.  This is needed to download plugins from https endpoints via a TLS-inspecting proxy server.
- fixes #386
While attaching `controller.httpsKeyStore` to init would also have fixed, this [forces enabling end-to-end TLS](https://github.com/jenkinsci/helm-charts/blob/330c61cebe3393b3d7fdd6216805338a59d4e7cd/charts/jenkins/templates/jenkins-controller-statefulset.yaml#L151), which isn't wanted.  We have created a secret containing the keystore and refer to it using `persistence.volumes` and just need init to mount it so Jenkins will start via proxy.
> Attach custom volume mounts to init container (fixes issue #386)

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/jenkins-controller-ingress.yaml
- charts/jenkins/templates/jenkins-controller-statefulset.yaml
Fixes "pathType must be specified" error when trying to deploy with value `controller.ingress.resourceRootUrl` on k8s >=v1.19.x.
- fixes #393
> Fix resource root url on k8s >=v1.19.x

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/_helpers.tpl
- charts/jenkins/tests/jcasc-config-test.yaml
- charts/jenkins/values.yaml
The current version of this chart does not allow the agent pod template to customize the value of `showRawYaml`.
https://github.com/jenkinsci/helm-charts/blob/b9557c959929b4db83dbde515ee3493bbff7d1af/charts/jenkins/templates/_helpers.tpl#L254
For those of us still looking at the legacy console output, that creates too much noise, making it difficult to understand and diagnose errors.
Other than that, it makes it impossible to use any sensitive information in the pod template.
- fixes https://github.com/jenkinsci/helm-charts/issues/401.
> Allow showRawYaml to be customized for the default agent's pod template.

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/jenkins-controller-statefulset.yaml
- charts/jenkins/tests/__snapshot__/jenkins-controller-statefulset-test.yaml.snap
- charts/jenkins/tests/jenkins-controller-statefulset-test.yaml
Signed-off-by: Alexis Martinier <a.martinier@gmail.com>
Allow to use template in podAnnotations for controller (usage ex: trigger a rollout when a custom config file have changed)
I have written a test case for `podAnnotations` template using **snapshot** feature of unittest.  
This could impact the CI like the `checksum/config`annotation could change (config.yaml update) and require a snapshot update using `-u` option. Developers could handle this on their local dev machine before submitting a PR
> feat(controller): use template for controller.podAnnotations

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES_SUMMARY.md
- charts/jenkins/templates/config.yaml
- charts/jenkins/tests/config-test.yaml
- charts/jenkins/values.yaml
Configure the plugin-installation-manager-tool to install the latest specified plugins.
This should help to bump the version of all the plugins to latest if specified when upgrading the helm.
For instance, if bumping a version of an explicit plugin, then `helm upgrade`, if it has an optional dependency then it will fail.
It adds the latest-specified flag -> https://github.com/jenkinsci/plugin-installation-manager-tool#cli-options
- https://github.com/jenkinsci/plugin-installation-manager-tool/issues/339
> Enable --latest-specified flag for the jenkins-plugin-cli in the init container

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/config.yaml
- charts/jenkins/unittests/__snapshot__/jenkins-controller-statefulset-test.yaml.snap
- charts/jenkins/unittests/config-test.yaml
- charts/jenkins/unittests/jenkins-controller-statefulset-test.yaml
- charts/jenkins/values.yaml
* Updated versions of default plugins
* Use verbose logging during plugin installation
* download the latest version of all plugin dependencies (Fixes #442)
- fixes #442
With `--latest false` we did not download latest versions of transitive dependencies. That caused warnings within Jenkins.
> update plugins & download latest dependencies

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES_SUMMARY.md
- charts/jenkins/templates/home-pvc.yaml
- charts/jenkins/unittests/home-pvc-test.yaml
- charts/jenkins/values.yaml
This change adds support for specifying additional labels for the
Jenkins home pvc.
Tests added
Changelog updated and version bumped
README.md and VALUES_SUMMARY.md updated.
Signed-off-by: Gavin Williams <fatmcgav@gmail.com>
> feat: Add support for adding pvc labels

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
Signed-off-by: Tim Jacomb <timjacomb1+github@gmail.com>
Wiki.jenkins.io is down, I got an email from artifacthub saying there was an issue with the icon
https://helm.sh/docs/topics/charts/#the-chart-yaml-file says we can use an svg so that should be better
> Update icon location

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES_SUMMARY.md
- charts/jenkins/ci/other-values.yaml
- charts/jenkins/unittests/jcasc-config-test.yaml
- charts/jenkins/values.yaml
Signed-off-by: joelee2012 <lj_2005@163.com>
The kubernetes plugin and inbound-agent are using `/home/jenkins/agent` as default workingDir,  but jenkins chart is still using '/home/jenkins' which may cause issue https://issues.jenkins.io/browse/JENKINS-58766.
> update workingDir to /home/jenkins/agent

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES_SUMMARY.md
- charts/jenkins/templates/jenkins-controller-pdb.yaml
- charts/jenkins/unittests/jenkins-controller-pdb-1.21-test.yaml
- charts/jenkins/unittests/jenkins-controller-pdb-test.yaml
- charts/jenkins/values.yaml
This can be useful to ensure that Jenkins controller doesn't get
restarted un-necessarily or un-expectedly.
Defaulted `maxUnavailable` to `0` in order to prevent Jenkins
controller pod being voluntarily terminated.
Add unit test and updated `VALUES_SUMMARY.md`
Signed-off-by: Gavin Williams <fatmcgav@gmail.com>
> feat: Add support for creating a Pod Disruption Budget for Jenkins controller

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES_SUMMARY.md
- charts/jenkins/templates/jenkins-controller-statefulset.yaml
- charts/jenkins/unittests/jenkins-controller-statefulset-test.yaml
- charts/jenkins/values.yaml
This PR allows for configuration of termination log pathing and termination log policy. It configures the StatefulSet (Jenkins container).
Termination logs could be routed to persistent storages and termination log policies can incorporate last chunk of container log output using different policies.
- fixes #433 
This is my very first open source contribution. I adhered to the contribution guide. If I made an error along the way, please take the time to lesson me about it, so that I can avoid such mistakes in future contributions. Thank you! :)
> Add support for container termination logs

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES_SUMMARY.md
- charts/jenkins/templates/_helpers.tpl
- charts/jenkins/unittests/jcasc-config-test.yaml
Closes https://github.com/jenkinsci/helm-charts/issues/466
Signed-off-by: Dominykas Blyžė <hello@dominykas.com>
- fixes #466
There currently is a default label added for the agent pods - I chose to keep `podLabels` as _additional_ labels, but happy to change it so that instead the old value is used as a default.
---
I did not bump the version/CHANGELOG, because I don't know when would this be merged or what version it would become...
> Support custom agent pod labels

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/config-init-scripts.yaml
- charts/jenkins/unittests/config-init-scripts-test.yaml
Runs `tpl` on all inlined `init` scripts. This is useful when you want to generate a single template that can utilize things like `{{ .Values.some.val }}` inside. 
Follows the same pattern currently used in `config.yaml`
CC - @timja @wmcdona89 @maorfr
> feat: Adding tpl to init scripts config map

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/jenkins-controller-statefulset.yaml
- charts/jenkins/unittests/jenkins-controller-statefulset-test.yaml
Currently, there is no way of just add custom arguments the default container args. One has to override it completely while copying the default values into the override array. Some of the default options (e.g. port number) are retrieved from values.yaml fields. Using the `controller.overrideArgs` lacks the ability of just referring to such fields.
This PR adds `tpl` to `controller.overrideArgs` to make it easier for Chart users to reuse values across the configuration.
> Templates in override args

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/_helpers.tpl
- charts/jenkins/templates/jenkins-controller-statefulset.yaml
Previously, the config reload sidecar's request URL pointed to the `targetPort`, which, when the httpsKeystore is in use, is set to `8443` in our configuration. The sidecar ends up POSTing HTTP->HTTPS, which results in a `BadStatusLine` error when the sidecar attempts a configuration reload. This PR fixes the REQ_URL environment variable's template to correctly use the defined `httpsKeyStore.httpPort` when the httpsKeyStore is enabled, like other uses of `targetPort` do.
@torstenwalter @justusbunsi @nikonorovi
> Fix config reload request url when httpsKeystore in use

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/jenkins-controller-statefulset.yaml
- charts/jenkins/values.yaml
When deploying on a Kubernetes cluster 1.14 (technical debt, I know😅), I encountered an issue with the startupProbe : Kubernetes refused to create the Statefulset because this type of probe was added in Kubernetes 1.16.
So I made this fix in order to make it work on legacy Kubernetes clusters like mine.
N/A
> Fix definition of startupProbe when deploying on a Kubernetes cluster < 1.16

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/values.yaml
Have a look at #541 the current example is a bit misleading as one could thing that one should specify list entries.
So instead of:
```yaml
agent:
workspaceVolume:
- type: Nfs
readOnly: false
serverAddress: "192.0.2.0"
serverPath: /var/lib/containers
```
one should specify it like:
```yaml
agent:
workspaceVolume:
type: Nfs
readOnly: false
serverAddress: "192.0.2.0"
serverPath: /var/lib/containers
```
- fixes #541
> Improve workspaceVolume example

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES_SUMMARY.md
- charts/jenkins/unittests/__snapshot__/jenkins-controller-statefulset-test.yaml.snap
- charts/jenkins/unittests/config-test.yaml
- charts/jenkins/unittests/jenkins-controller-statefulset-test.yaml
- charts/jenkins/values.yaml
Bump configuration-as-code plugin to 1414.v878271fc496f
- fixes #604 
- [x ] [DCO](https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ x] Chart Version bumped
- [ x] CHANGELOG.md was updated
> Bump configuration-as-code plugin to 1414.v878271fc496f

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES_SUMMARY.md
- charts/jenkins/templates/_helpers.tpl
- charts/jenkins/unittests/jcasc-config-test.yaml
- charts/jenkins/values.yaml
When specifying podTemplates for the Jenkins Agent configuration, there is always a default agent configuration which you cannot get rid of. This PR adds a flag which allows you to disable to default Jenkins Agent configuration which defaults to false, the current behaviour.
- fixes #608
> Added Value for disabling default Jenkins Agent

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/_helpers.tpl
- charts/jenkins/unittests/jcasc-config-test.yaml
Currently, the namespace for Kubernetes cloud agents is set to the chart namespace however a value does exist for its Values.agent.namespace.
This change should allow the user to set a different namespace for agents in general and also overwrite the namespace for additional agents.
- fixes #
> Make namespace overwritable for agents and additional agents.

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES_SUMMARY.md
- charts/jenkins/templates/_helpers.tpl
- charts/jenkins/unittests/jcasc-config-test.yaml
- Implementation / reasoning described in #616
- ~~Also updates whitespace in the unit tests - they were failing for me locally. Do they even get executed in CI? I don't see anything in the logs (even though the command is mentioned in `ct.yaml`)?~~ It seems they're only failing for me locally... Is it due to helm version mismatch or smth? Seems CI is running 3.4, while I'm running 3.8...
- Fixes #616
- Alternative for #623 / Workaround for #592
> Add `legacyRemotingSecurityEnabled` flag

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/jenkins-controller-servicemonitor.yaml
There are metrics that are not used anywhere and hence there should be the option to drop them through values configuration, e.g. regex: ^kubernetes_cloud_pipeline_pod.+
Signed-off-by: Vlad Gunda <vlad.gunda@ext.walter-group.com>
- fixes #
> Allow relabeling of unused metrics

- charts/jenkins/Chart.yaml
- charts/jenkins/README.md
- charts/jenkins/values.yaml
Remove references to `enableXmlConfig` which was removed in c00b41ac
- fixes #635
> remove references to enableXmlConfig which was removed in c00b41ac

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/jenkins-controller-statefulset.yaml
- charts/jenkins/unittests/secret-existing-test.yaml
Signed-off-by: Sylvain Pasche <sylvain.pasche@gmail.com>
#645 changed how secrets are named in JCasC.
This restore previous behavior to keep compatibility.
> Fix path of projected secrets from additionalExistingSecrets

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES_SUMMARY.md
- charts/jenkins/templates/jenkins-backup-cronjob.yaml
- charts/jenkins/unittests/jenkins-backup-cronjob-test.yaml
- charts/jenkins/values.yaml
Allow setting `imagePullSecret` for backup job.
> Add `backup.imagePullSecretName`

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/_helpers.tpl
- charts/jenkins/templates/jcasc-config.yaml
Signed-off-by: Miles Wilson <wilson.mil@icloud.com>
This PR abstracts out the JCasC configmap name generation to a named template called `jenkins.casc.configName`. Most importantly, this allows it to be overridden in downstream, which is my goal for making this change without causing problems from changing `jenkins.fullname`
- fixes #650 
Thanks for your notes @timja
> abstracted JCasC ConfigMap names as named template

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/jenkins-controller-statefulset.yaml
- charts/jenkins/unittests/jenkins-controller-statefulset-test.yaml
For plugin installation a volume with emptyDir is created/used. If the plugin installation is disabled the volume still gets created but isn't used anywhere. This can lead to problems in combination with cluster autoscaling since pods with local storage won't get evicted by default.
- relates to #569
> Don't create plugins volume when not needed

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/_helpers.tpl
- charts/jenkins/unittests/jcasc-config-test.yaml
- charts/jenkins/values.yaml
Signed-off-by: Max Nitze <max.nitze@gmx.de>
`projectNamingStrategy` is currently hard-coded as `"standard"` in the `jcasc-default-config.yaml` file. Unfortunately the JCasC Plugin is not able to merge it with another configuration file, in case it is configuring a non-string value for it.
Here is an example from the configuration of the [role-strategy](https://plugins.jenkins.io/role-strategy/) plugin:
```
$ cat /var/jenkins_home/casc_configs/jcasc-default-config.yaml
jenkins:
...
projectNamingStrategy: "standard"
...
$ cat /var/jenkins_home/casc_configs/role-strategy.yaml
jenkins:
projectNamingStrategy:
roleBased:
forceExistingJobs: true
authorizationStrategy:
roleBased:
...
```
This leads to:
```
2022-08-08 13:46:39.788+0000 [id=93]    WARNING …
```
> Make projectNamingStrategy in default config configurable

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/_helpers.tpl
- charts/jenkins/unittests/jcasc-config-test.yaml
- charts/jenkins/values.yaml
In #699 the option to add additional containers to the default agent templates was introduced. In that change it was also made possible to configure the `command` and `args` of the agent containers as lists. That feature is not supported by the [Jenkins Kubernetes Plugin](https://plugins.jenkins.io/kubernetes/).
- none
> Remove option to provide command and args in agent as YAML

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/jenkins-controller-podmonitor.yaml
- charts/jenkins/values.yaml
Signed-off-by: Chuyen Pham <pkchuyen@users.noreply.github.com>
enabling Google Managed prometheus when running Jenkins on GKE cluster
- [ x] [DCO](https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ x] Chart Version bumped
- [ x] CHANGELOG.md was updated
> Support Google Managed Prometheus monitoring

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/jenkins-controller-svc.yaml
- charts/jenkins/unittests/jenkins-controller-svc-test.yaml
- charts/jenkins/values.yaml
Signed-off-by: Daniel Robinson <dan.robinson21@gmail.com>
Adds an extra argument to extraPorts in order to specify an optional targetPort
Makes extraPorts more customisable instead of always setting targetPort = port in the controller.svc template.
- fixes #
> Customise extraports

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/jenkins-controller-statefulset.yaml
- charts/jenkins/unittests/jenkins-controller-statefulset-test.yaml
- charts/jenkins/values.yaml
The JCasC plugin supports three variations of providing the value to this environment variable.
Path to a folder containing a set of config files. For example, /var/jenkins_home/casc_configs.
A full path to a single file. For example, /var/jenkins_home/casc_configs/jenkins.yaml.
A URL pointing to a file served on the web. For example, https://acme.org/jenkins.yaml.
The third option is not supported by the helm chart.
This would help to externalize the whole jenkins-casc.yaml from the values.yaml file and store it in git.
- fixes #530
> Remote configuration url

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/jenkins-controller-statefulset.yaml
Signed-off-by: Tom Walker <walker.thomas.p@gmail.com>
By moving the use of the `.Values.containerEnv` value to the top of the `env` block, it means that all other env values can reference these values, in the same way that `JAVA_OPTS` value currently references `POD_NAME`.
The main use case of this for me is being able to pass in the Java truststore password as an Env Var like `TRUSTSTORE_PASSWORD` and then in `.Values.javaOpts` reference it like `-Djavax.net.ssl.trustStorePassword=$(TRUSTSTORE_PASSWORD)`.
> Move use of 'containerEnv' to top of 'env' block for 'jenkins' Container

- charts/jenkins/Chart.yaml
- charts/jenkins/README.md
There are no technical changes in this PR.  This PR is simply adding in some extra information in the Configuration as Code section of the helm chart.  Speaking from experience, as someone relatively new in Helm charts, I got stuck on a goose chase trying to break out my Config as Code scripts.  Your initial instinct is to check the Config as Code plugin on how to split CasC config files, and of course they recommend updating the `CASC_JENKINS_CONFIG` variable.  This presents a red herring for people, as this doesn't work well with the Helm chart (in my experience).  The better solution was separate values files with the config scripts, which wasn't immediately apparent for me.  If you all feel that this could be useful, then feel free to merge the info.
I had an open issue to add …
> Czap bran patch 1 cas c readme

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/jenkins-controller-statefulset.yaml
- charts/jenkins/templates/secret-https-jks.yaml
- charts/jenkins/unittests/jcasc-config-test.yaml
- charts/jenkins/unittests/jenkins-controller-statefulset-test.yaml
- charts/jenkins/values.yaml
- This allows for sidecars to provide TLS certificates and to signal a controller to reload certificates when they change
- Also optionally disables the creation of secrets which won't be used if they're being provided by an external issuer
> Enable sourcing TLS certs from external issuers

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/_helpers.tpl
- charts/jenkins/templates/jenkins-controller-statefulset.yaml
- charts/jenkins/unittests/jcasc-config-test.yaml
- charts/jenkins/unittests/jenkins-controller-statefulset-test.yaml
- disables the volume mount of `jenkins-https-keystore` on the initContainer when `disableSecretMount` is set to true. Currently, setting this variable to true will prevent jenkins from starting up as it will attempt to mount a secret on the init container which does not exist (and, if `disableSecretMount` is set to true, is not wanted).
- Corrects the definition of an environment variable. This was mistakenly defined with keys of `name` and `jenkinsTunnel` rather than `name` and `value` due to an incorrectly handled merge
- This corrects bugs from #814
> Disable secret mount on initContainer

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
The Jenkins project strives for a low barrier of entry for everyone. This principle is partly achieved by not requiring (new) contributors to perform any sort of additional chores to get their changes proposed into the codebase, endorsed by the Jenkins project governance.
Signing commits should be voluntary for contributors, that's how repositories are handled within the jenkinsci organization. Therefore, I recommend uninstalling the DCO bot, to comply with the overall project governance.
Contributors, who want to sign off their work, can do that nonetheless.
> Drop DCO requirement

- .github/workflows/sync-lts.yaml
While comparing https://github.com/garethjevans/jenkins-version with https://github.com/jenkins-infra/jenkins-version I see no difference in commits, but a repository that is much lesser maintained than ours.
Is there a particular reason to use the fork of our repository, if it contains no new content?
> Move to jenkins-infra version of 'jenkins-version'

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/values.yaml
I cherry-picked this commit from the other PR because I can't rebase it.
GH actions expect a chart update for that one:
>  ✖︎ jenkins => (version: "4.3.13", path: "charts/jenkins") > Chart version not ok. Needs a version bump!
Closes https://github.com/jenkinsci/helm-charts/pull/782
> Fix typo in 'controller'

- .github/workflows/lint-test.yaml
Let's see if we can use a newer version over one from 2018.
> Update python in lint-test from 3.7 to 3.11.2

- .github/workflows/sync-lts.yaml
Instead of running every 15 minutes all day long, the change proposed slows it down to run hourly on Wednesday's, the only day of the week LTS releases are published.
Possible typo issues are covered by https://github.com/jenkinsci/helm-charts/pull/843
> Slow down LTS sync schedule

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
Fixes https://github.com/jenkinsci/helm-charts/issues/852 by releasing a newer version.
I tried to replay the GH workflow, but all it did was re-uploading the archive. Bumping the charts to skip 4.2.21 silently seems to be the easiest solution.
> Bump chart version

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/ci/other-values.yaml
- charts/jenkins/unittests/__snapshot__/jenkins-controller-statefulset-test.yaml.snap
- charts/jenkins/unittests/config-test.yaml
- charts/jenkins/unittests/jenkins-controller-statefulset-test.yaml
- charts/jenkins/values.yaml
Resolves a conflict with the pipeline plugin and git:
```
Plugin workflow-aggregator:596.v8c21c963d92d (via workflow-cps:3691.v28b_14c465a_b_b_) depends on git:5.1.0, but there is an older version defined on the top level - git:5.0.0,
```
I chose to bump all plugins to the version defined in the bom to prevent further conflicts.
> Update bundled plugins

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/README.md
These changes resolve spelling mistakes found within `charts/jenkins/README.md`.
* A misspelled word, `seperated`, has been corrected to `separated` following [the Merriam-Webster spelling of the word](https://www.merriam-webster.com/dictionary/separated).
* A misspelled word, `seperate`, has been corrected to `separate` following [the Merriam-Webster spelling of the word](https://www.merriam-webster.com/dictionary/separate).
> Fix spelling mistakes in charts/jenkins/README.md.

- .github/PULL_REQUEST_TEMPLATE.md
A small change, simplifying the PR template and removing the outdated helm/charts default text, that hopefully helps contributors to bump charts and add changelog entries, when modifying files guarded by GH actions.
```[tasklist]
```
> Outline how to bump charts in PRs

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES_SUMMARY.md
- charts/jenkins/templates/_helpers.tpl
- charts/jenkins/values.yaml
This PR allows the kubernetes API server URL to be configurable via `kubernetesURL` in the chart values.
Previously it was hard coded to `https://kubernetes.default` which is now the default value.
```[tasklist]
```
> feat: Make the k8s API server URL configurable

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/_helpers.tpl
- charts/jenkins/unittests/jcasc-config-test.yaml
- charts/jenkins/values.yaml
Pod templates for agents support liveness probes:
But the chart does not. This PR adds the possibility to configure liveness probes on all containers, main and sidecar, of your agent pods.
```[tasklist]
```
To get the tests working, I had to update a lot of IDs in the `jcasc-config-test.yaml` file. Is this intended? Is there any way to make this easier than looking at the failing tests and copying the ids to the tests file (25 times)?
> Add config keys for liveness probes on agent containers

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES_SUMMARY.md
- charts/jenkins/templates/_helpers.tpl
- charts/jenkins/unittests/jcasc-config-test.yaml
- charts/jenkins/values.yaml
extend configuration options with extra parameter jnlpregistry
- Fixes #867
```[tasklist]
```
> add support for customizing kubernetes jnlpregistry

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES_SUMMARY.md
- charts/jenkins/templates/home-pvc.yaml
- charts/jenkins/unittests/home-pvc-test.yaml
- charts/jenkins/values.yaml
Add the ability to clone the home PVC from an existing volume, GCP snapshot, etc as described in [CSI Volume Cloning](https://kubernetes.io/docs/concepts/storage/volume-pvc-datasource/). Not only is this useful for CI/testing against the jenkins chart, this can also be used to restore from a backup or to facilitate a major jenkins version upgrade.
```[tasklist]
```
i added tests
> feat: allow cloning home-pvc from custom dataSource

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/unittests/__snapshot__/jenkins-controller-statefulset-test.yaml.snap
- charts/jenkins/unittests/config-test.yaml
- charts/jenkins/unittests/jenkins-controller-statefulset-test.yaml
- charts/jenkins/values.yaml
We had plugin dependency issues with `azure-ad` plugin after updating to the latest jenkins helm chart version (4.6.0)
```
...
io.jenkins.tools.pluginmanager.impl.AggregatePluginPrerequisitesNotMetException: Multiple plugin prerequisites not met:
Plugin azure-ad:385.v5d9f88612dd2 depends on configuration-as-code:1670.v564dc8b_982d0, but there is an older version defined on the top level - configuration-as-code:1647.ve39ca_b_829b_42,
Plugin azure-ad:385.v5d9f88612dd2 (via matrix-auth:3.2) depends on configuration-as-code:1670.v564dc8b_982d0, but there is an older version defined on the top level - configuration-as-code:1647.ve39ca_b_829b_42
...
```
- Fixes plugin dependency issues with `azure-ad:385.v5d9f88612dd2`
If you modified files in the `./charts/jenkins/` directory, please also …
> Update jcasc plugin

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/jenkins-controller-ingress.yaml
Improving DRY principle support on Jenkins Controller Ingress host name
- Fixes #
The change is intending to support the following syntax in a _values.yaml_ such as:
```
global:
jenkinsHostname: "jenkins.my-org.com"
controller:
ingress:
enabled: true
hostName: "{{ .Values.global.jenkinsHostname }}"
resourceRootUrl: "{{ .Values.global.jenkinsHostname }}"
tls:
- hosts:
- "{{ .Values.global.jenkinsHostname }}"
```
> Improving DRY principle support on Jenkins Controller Ingress host name

- charts/jenkins/Chart.yaml
- charts/jenkins/unittests/__snapshot__/jenkins-controller-statefulset-test.yaml.snap
- charts/jenkins/unittests/config-test.yaml
- charts/jenkins/unittests/jenkins-controller-statefulset-test.yaml
- charts/jenkins/values.yaml
currently when installing jenkins with helm chart on a new kubernetes cluster the kubernetes plugin requires an upgrade in order to function
upgrading the kubernetes plugin to it's latest version. 
also suggested here: https://community.jenkins.io/t/error-while-launching-agent/9385/5
- Fixes #
```[tasklist]
- I bumped the "version" for kubernetes plugin key in `./charts/jenkins/values.yml`.
```
> Upgrade kubernetes plugin version

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES_SUMMARY.md
- charts/jenkins/templates/_helpers.tpl
- charts/jenkins/templates/jenkins-controller-statefulset.yaml
- charts/jenkins/unittests/jenkins-controller-statefulset-test.yaml
- Fixes #868 
This should make the startup routine of Jenkins more stable and have fewer race conditions. When the existing implementation of the sidecar detects configmap/secret changes, it calls an endpoint on Jenkins to reload CasC, however since the sidecar and the Jenkins begin booting up at the same time, this introduces several potential race conditions:
- the endpoint to reload CasC may be called before Jenkins has started up and result in various errors (e.g. CSRF problems)
- the endpoint to reload CasC may be called while Jenkins is initializing original CasC (unverified, but in theory possible - there is some evidence that this might have happened, although not concrete proof)
- the config-reload sidecar might be rewriting files while Jenkins is reading them, resulting in …
> Use config-reload container as an init container

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/jenkins-controller-statefulset.yaml
- charts/jenkins/unittests/jenkins-controller-statefulset-test.yaml
Add the config-init-script checksum into the controller statefullset pod annotations to trigger restart of the pod in case of updated init scripts.
- Fixes #678
```[tasklist]
```
> Add checksum for config-init-script into statefullset annotations

- .github/workflows/release.yaml
This PR add the last version changelog to the GitHub release body when a new chart version is published.
Tested on a fork, result:
- Chart bump: https://github.com/lemeurherve/jenkinsci-helm-charts/commit/77676f437ec49359d491ae29dbd74476a389bec1
- Corresponding release: https://github.com/lemeurherve/jenkinsci-helm-charts/releases/tag/jenkins-7.8.9
> chore: add last version changelog to the GitHub release

- .github/workflows/release.yaml
- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
This PR adds Artifact Hub annotation in the released chart so it can renders its integrated changelog: https://blog.artifacthub.io/blog/changelogs/
- Only the current version changes have to be included, not the full changelog.
- It's the simple form of Artifact Hub changes. Looking at the existing changelog, I'm not sure the more complete form will ever be needed.
- I had to strip emojis to avoid having the scalar value broke as single string and failing chart-releaser step:
<details>
```
📦 Add `artifacthub.io/changes` changelog annotation to the released chart.
Table example:
| plugin                | old version          | new version           |
|-----------------------|----------------------|-----------------------|
| kubernetes            | 3900.va_dce992317b_4 | …
```
> chore: add `artifacthub.io/changes` changelog annotation to the released chart

- .github/workflows/release.yaml
- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
This PR fixes Artifact Hub changes annotation by properly preprocessing the version changes from CHANGELOG.md:
- Remove empty lines
- Keep only ASCII characters (no emojis)
- One change per line
- Remove table(s) (lines starting by `|`)
Note that backticks aren't rendered on artifactthub.io changelog.
Fixup of:
- #949 
- #950 
```[tasklist]
```
Tested on a fork and on an Artifact Hub account I've setup for testing:
- Commit: https://github.com/lemeurherve/testchart/commit/b395c641ee25e71dee5d86d1564542f25606c9d2
- GitHub Release: https://github.com/lemeurherve/testchart/releases/tag/jenkins-0.1.9
- Artifact Hub changelog: https://artifacthub.io/packages/helm/testchart/jenkins?modal=changelog
> fix: proper `artifacthub.io/changes` annotation preprocessing

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
This PR restore the Artifact Hub notes location to avoid incorrect artifacthub.io changes annotations due to the move of the comment in CHANGELOG.md as noted in https://github.com/jenkinsci/helm-charts/pull/952#discussion_r1405484420
Corresponding GHA logs with wrong Chart.yaml annotations: https://github.com/jenkinsci/helm-charts/actions/runs/6998244499/job/19036090425
```yaml
artifacthub.io/changes: |
- Update base images from JDK 11 to JDK 17.
- 
```
Fixup of:
- #952 
```[tasklist]
```
> chore: restore Artifact Hub notes location in CHANGELOG.md

- .github/workflows/release.yaml
This PR runs run `release` GitHub Action only if there is at least a change in `./charts/**`.
- Fixes #
```[tasklist]
```
Same setting as the one we're using in https://github.com/jenkins-infra/helm-charts/blob/86569747e16096bcd20ea217db697f44dc2ae398/.github/workflows/release.yml#L6-L7
> chore: run `release` GitHub Action only if there is a chart change

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES_SUMMARY.md
- charts/jenkins/unittests/jcasc-config-test.yaml
- charts/jenkins/values.yaml
This PR updates the jenkins/inbound-agent tag from 3107 to 3192.
I haven't bumped the version key yet as I wanted to see what kind of version bump this should be. For the Debian-based image, this updates Debian from 11 to 12. This can be breaking in some cases.
- Fixes #
```[tasklist]
```
As far as I can tell, this is a breaking change since the Debian-based image now uses Debian bookworm.
> chore: Updated jenkins/inbound-agent to 3192

- .github/workflows/sync-lts.yaml
- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/_helpers.tpl
- charts/jenkins/unittests/jcasc-config-test.yaml
- charts/jenkins/values.yaml
- Fixes #634
- Adds the option to set the `credentialsId` for the main cloud and the additional clouds.
```[tasklist]
```
I did not do the tasks in "Submitter checklist" because I want to gather feedback on my changes. If I'm going in the right direction I will be happy to do all those tasks!
I tried to do the `additionalClouds` feature the same way the `additionalAgents` feature was built in: by looping through the items and merging to the main template. I also stored the state before the loop and restored it after the loop ends.
> Add multi-cloud support (#634)

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/_helpers.tpl
- charts/jenkins/unittests/__snapshot__/jenkins-controller-statefulset-test.yaml.snap
- charts/jenkins/unittests/config-test.yaml
- charts/jenkins/unittests/jcasc-config-test.yaml
- charts/jenkins/unittests/jenkins-controller-statefulset-test.yaml
- charts/jenkins/values.yaml
https://github.com/jenkinsci/kubernetes-plugin/pull/1489 introduces the possibility to use ephemeral storage volumes in the Build pod specification. This change makes it explicit that this volume type is supported by the Helm Chart.
- Fixes #982
During implementation I realized that there is a fallback/default behavior for when the desired type is not listed/implemented. Since the `kubernetes` plugin had to be updated anyways to allow that type, I continued implementing this PR.
> Add support for generic ephemeral storage

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
This will merge #991 and #992. Also, this makes the artifacthub.io/images annotation more explicit
- Fixes #
```[tasklist]
```
> chore: Prefixed artifacthub.io/images with docker.io

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
This should merge #996 and #998
- Fixes #
```[tasklist]
```
I'll make some changes to the Renovate config at a later moment that should allow for the jenkins-inbound-agent image to be prefixed with docker.io
> chore: Remove docker.io prefix for inbound-agent

- .github/workflows/linter.yml
- .gitleaksignore
Disables the new GitLeaks linter included in super-linter, as it keeps popping up with new false-positives.
- Fixes #
```[tasklist]
```
> chore: Disabled GitLeaks linter

- .gitleaksignore
- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES_SUMMARY.md
- charts/jenkins/templates/jenkins-controller-statefulset.yaml
- charts/jenkins/unittests/jenkins-controller-statefulset-test.yaml
Fix controller.sidecars.additionalSidecarContainers 
subsume https://github.com/jenkinsci/helm-charts/pull/1001
Missing unit test didn't catch this regression so adding one
Fix controller.sidecars.additionalSidecarContainers renaming and add tests
```[tasklist]
```
> fix: controller.sidecars.additionalSidecarContainers renaming and add tests

- .github/renovate-config.json5
- .github/renovate-postupgrade.sh
Fixed the Renovate changelog entry by handling the depName that is supplied twice.
- Fixes #1028 
```[tasklist]
```
The solution is a bit hacky, but it works and seems robust, since the script should never be called with multiple unique dependency names.
> chore: Fixed Renovate changelog entry

- .github/renovate-config.json5
Fixes the Renovate configuration for Jenkins LTS updates
- Fixes #1030 
```[tasklist]
```
I had a package rule for `jenkins/jenkins` to specify a more strict versioning than is default for Renovate. This didn't get applied to `docker.io/jenkins/jenkins`
> fix(renovate): Fix Renovate configuration for Jenkins LTS

- .github/renovate-config.json5
- .github/workflows/lint-test.yaml
Improves Renovate's version detection for Python versions for GitHub Actions
- Fixes the problem seen in #1067
```[tasklist]
```
@timja this will prevent Renovate from opening these types of PRs until the Python version is supported by actions/setup-python.
> chore: improved renovate config for detecting python updates

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES.md
- charts/jenkins/templates/jcasc-config.yaml
- charts/jenkins/unittests/jcasc-config-test.yaml
- charts/jenkins/values.yaml
This PR provides a new parameter `controller.JCasC.configMapAnnotations` that allows for customizing the annotations on all of the JCasC config map resources that are templated out.
- Fixes #1120 
> Add controller.JCasC.configMapAnnotations to allow setting annotations on the JCasC ConfigMaps

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES.md
- charts/jenkins/templates/_helpers.tpl
- charts/jenkins/unittests/__snapshot__/jcasc-config-test.yaml.snap
- charts/jenkins/values.yaml
This pr exposes the configuration of `inheritYamlMergeStrategy` on the default agent via the chart values. The default value for this is set to `false` to match the default behaviour of the JCasC plugin.
The changes have been tested against a live jenkins deployment and the configuration is applied and behaves as expected. Tested with both the default value and overridden to `true`.
```[tasklist]
```
> feat: Configure inherit yaml merge strategy

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES.md
- charts/jenkins/templates/jenkins-controller-statefulset.yaml
- charts/jenkins/unittests/jenkins-controller-statefulset-test.yaml
- charts/jenkins/values.yaml
We host multiple jenkins controllers in one of our EKS clusters and we need to be able to spread the controller pods across topology domains.
```[tasklist]
```
> feat: add controller.topologySpreadConstraints

- .github/workflows/renovate.yaml
This PR changes the schedule to make Renovate run hourly and on push to main to more closely resemble the behavior of the Renovate GitHub App.
- Fixes #
```[tasklist]
```
> chore: run renovate hourly and on push

- .github/linters/.textlintrc
- .github/workflows/linter.yml
- CONTRIBUTING.md
- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/UPGRADING.md
Updates super-linter to v6.7.0 as in #1117. Also disables checkov as it is too strict for the default Helm template. Fixes some NATURAL_LANGUAGE issues and ignores some other.
- Fixes #
```[tasklist]
```
> chore(deps): update super-linter to v6.7.0

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES.md
- charts/jenkins/templates/_helpers.tpl
- charts/jenkins/unittests/__snapshot__/jcasc-config-test.yaml.snap
- charts/jenkins/unittests/jcasc-config-test.yaml
- charts/jenkins/values.yaml
Fixes jenkinsci/helm-charts#901
Add capabilities for set skipTlsVerify and  usageRestricted flags for multicloud configuration. The flag are defaulted to false
```[tasklist]
```
> feat: add support for usageRestricted and skipTlsVerify

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES.md
- charts/jenkins/templates/_helpers.tpl
- charts/jenkins/unittests/__snapshot__/jcasc-config-test.yaml.snap
- charts/jenkins/values.yaml
- Addresses #1173
```[tasklist]
```
> feat: add support for kubernetes plugin garbage collection

- .github/workflows/release.yaml
- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
Publish also the chart to the GHCR registry
- Fixes
https://github.com/jenkinsci/helm-charts/issues/1180
```[tasklist]
```
This was inspired from https://github.com/fluxcd-community/helm-charts/pull/94/files
Chart is published on both location (the traditional GH page and the GH package)
I've tested the workflow change on my fork
https://github.com/jonesbusy/helm-charts/actions/runs/10828217018
> Jenkins Helm chart is now also published to GitHub packages registry (oci://ghcr.io/jenkinsci/helm-charts/jenkins)

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES.md
- charts/jenkins/templates/rbac.yaml
- charts/jenkins/unittests/rbac-test.yaml
- charts/jenkins/values.yaml
OpenShift by default has very stringent pod security requirements for containers that often don't neatly align with upstream k8s Pod Security Standards. The "nonroot-v2" SecurityContextConstraint aligns most closely with the "restricted" pod security standard, but must be explicitly granted to a service account in order to be used. Granting the Jenkins service account permission to use the "nonroot-v2" SCC allows the StatefulSet to deploy on an OpenShift cluster.
- Fixes #1207 
```[tasklist]
```
- Note that to grant this SCC to Jenkins, the Helm chart needs to be deployed by a user with cluster-admin (or similar) permissions. Does this need to be noted in other documentation?
- Question for …
> feat: Add SCC RBAC for OpenShift

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/auto-reload-config.yaml
- charts/jenkins/templates/jcasc-config.yaml
replace '+' with '_' in chart version.
flux will version chart with <chart-version>+<revision> when using revision reconciliation strategy.  This break deployment.
- Fixes #
deployment via flux
```
Helm upgrade failed for release jenkins/jenkins with chart jenkins@5.6.1+087b605ce3dd.11: 
cannot patch "jenkins-jenkins-config-credentials" with kind ConfigMap: 
ConfigMap "jenkins-jenkins-config-credentials" is invalid: 
metadata.labels: Invalid value: "jenkins-5.6.1+087b605ce3dd.11":
```
```[tasklist]
```
> replace invalid  "+" with valid character

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/home-pvc.yaml
- charts/jenkins/templates/jenkins-controller-ingress.yaml
Add tpl support for persistence.storageClassName in home-pvc.yaml
--> Add tpl support for controller.ingress parameters(ingressClassName, annotations, hostname) in jenkins-controller-ingress.yaml
- Fixes #
```[tasklist]
```
> Extend DRY support for persistence and Ingress

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES.md
- charts/jenkins/templates/jenkins-controller-svc.yaml
- charts/jenkins/unittests/jenkins-controller-svc-test.yaml
- charts/jenkins/values.yaml
Adds the option to set the `publishNotReadyAddresses` flag on the controller service. This allows traffic to get to the controller before its pod reports itself ready.
The Jenkins controller has its own way of dealing with requests while it is still starting. It shows a startup page until the service is ready. This also allows the "auto-refresh when done" feature when doing a restart from the UI to work (again).
```[tasklist]
```
This flag was broken in very early Kubernetes releases (see https://github.com/kubernetes/kubernetes/issues/58662 for example). So this feature is not working on Jenkns instances running in Kubernetes <=1.11. Which should be okay, I think :smile:
> Add option to publish not-ready addresses

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES.md
- charts/jenkins/templates/jenkins-controller-statefulset.yaml
- charts/jenkins/templates/service-account-agent.yaml
- charts/jenkins/templates/service-account.yaml
- charts/jenkins/unittests/__snapshot__/jenkins-controller-statefulset-test.yaml.snap
- charts/jenkins/values.yaml
By default, kubernetes enables "automountServiceAccountToken" for all pods, see https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#opt-out-of-api-credential-automounting.
This poses a security risk, as pods might get kube-api permissions unintentionally.
More specifically, this fails security compliance tests:
https://learn.microsoft.com/en-us/azure/governance/policy/samples/built-in-policies
https://www.azadvertizer.net/azpolicyadvertizer/kubernetes_block-automount-token.html
Solution - Disable "automountServiceAccountToken", create projected volume for the token, and mount it on relevant containers
This does not effect default behavior, though if someone is looking to comply with security requirements and disable this, they must also manually mount the …
> Allow setting automountServiceAccountToken

- .github/renovate-config.json5
This PR fixes the jenkins/inbound-agent versioning regex.
I had some misconceptions about the versioning string. I interpreted `3283.v92c105e0f819-8` as `<major>.<minor>-<patch/build>`. The way I understand it now is `<major/remoting-version>-<minor/build/inbound-agent-version>`. As I found out, Renovate only supports numeric versions, and thus only the parts `3283` and `8` can be parsed. I know called these major and minor respectively, although they can be any combination of `major`, `minor`, `patch`, and `build`. Please advise if you'd like me to use another combination for this.
- Fixes #
```[tasklist]
```
> fix: fix renovate jenkins/inbound-agent versioning regex

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/templates/_helpers.tpl
- charts/jenkins/unittests/__snapshot__/jcasc-config-test.yaml.snap
This PR fixes an issue where the agentListenerPort in Jenkins does not update correctly when modified via Helm values. Specifically, even though the slaveAgentPort is set correctly in the Jenkins container's startup command and environment variables, the /var/jenkins_home/config.xml file retains the default value of 50000, causing Jenkins to continue listening on the incorrect port.
- Fixes #
```[tasklist]
```
> fix: Update Jenkins agentListenerPort in config.xml to reflect Helm

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES.md
- charts/jenkins/unittests/__snapshot__/jenkins-controller-statefulset-test.yaml.snap
- charts/jenkins/values.yaml
This PR updates Jenkins from JDK17 to JDK21. This new JDK LTS has been supported in the LTS version of Jenkins for quite a while: https://www.jenkins.io/doc/book/platform-information/support-policy-java/
- Fixes #
```[tasklist]
```
Not sure what you think about the timing of updating the JDK version. Also; would you prefer a different version bump or is this correct?
> fix: update jenkins/jenkins to 2.492.2-jdk21

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES.md
- charts/jenkins/values.yaml
- Fixes an incorrectly declared default value (and type in docs), which was resulting in a warning in Helm: `coalesce.go:286: warning: cannot overwrite table with non table`
> fix: correct type / default value

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/VALUES.md
- charts/jenkins/unittests/__snapshot__/jenkins-controller-statefulset-test.yaml.snap
- charts/jenkins/values.yaml
This PR reverts the update of k8s-sidecar as `1.30.4` and `1.30.5` are both broken. The apparent cause is https://github.com/python/cpython/issues/135408. There's many projects having the same issue as a result.
```[tasklist]
```
> Reverting update of k8s-sidecar due to upstream bug

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/unittests/__snapshot__/config-test.yaml.snap
- charts/jenkins/unittests/__snapshot__/jenkins-controller-statefulset-test.yaml.snap
- charts/jenkins/unittests/config-test.yaml
- charts/jenkins/unittests/jenkins-controller-statefulset-test.yaml
Fixes snapshot tests breaking on automated chart version bumps by using `renderHelmLabels: false` in tests.
**Context**:
- Follow-up to https://github.com/jenkinsci/helm-charts/pull/1430#discussion_r2246464837
- Automated PRs that bump chart versions keep failing tests like https://github.com/jenkinsci/helm-charts/actions/runs/16637614349/job/47081568241#step:8:170 
**The Problem**: 
Snapshots hardcode the helm chart version (e.g. `helm.sh/chart: jenkins-5.8.73`), so when automated tools bump the version, tests fail because the snapshot expects the old version but gets the new one. The label got added in my previous PR here https://github.com/jenkinsci/helm-charts/pull/1430
**The Fix**:
Use `renderHelmLabels: false` in snapshot tests so they don't include the dynamic version label. Much …
> test: unittest fix - allow helm version label to be dynamic

- .github/renovate-entrypoint.sh
Last 3 versions have been broken without files attached for download:
Downgrade to release before the last working one as I've switched it to the release datasource it should only fetch actually released ones now
- Fixes #
```[tasklist]
```
> Downgrade jenkinx-jx-version

- .github/workflows/renovate.yaml
Reverts jenkinsci/helm-charts#1445
See if this is related to dependency update failures
> Revert "chore(deps): update renovatebot/github-action action to v43.0.6"

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
- charts/jenkins/unittests/__snapshot__/jenkins-controller-statefulset-test.yaml.snap
- charts/jenkins/unittests/jenkins-controller-statefulset-test.yaml
Fixes checksum calculation in helm unittest that caused Renovate PRs to fail CI checks.
- Should fix #1456
- Adds missing `renderHelmLabels: false` to "render pod annotations" test  
- Ensures chart version changes don't break unit tests
- Issue: https://github.com/jenkinsci/helm-charts/issues/1456
- Failed Renovate PR: https://github.com/jenkinsci/helm-charts/pull/1438
- Failed CI job: https://github.com/jenkinsci/helm-charts/actions/runs/16853856504/job/47744007632?pr=1438
- Related fix attempt: https://github.com/jenkinsci/helm-charts/pull/1444
The "render pod annotations" test was missing `renderHelmLabels: false`, causing checksum to include chart version. When Renovate updated from 5.8.75 → 5.8.76, checksums became non-deterministic between environments.
- Add `renderHelmLabels: …
> fix: make unittest checksum calculation deterministic

- charts/jenkins/CHANGELOG.md
- charts/jenkins/Chart.yaml
Fix deprecated url. [docker-inbound-agent](https://github.com/jenkinsci/docker-inbound-agent) repository is deprecated and `jenkins/inbound-agent` is now built from the [docker-agent](https://github.com/jenkinsci/docker-agent/) repo, but we forgot to update the reference in `charts/jenkins/Chart.yaml`.
> fix: Fix docker-agent git repo url in Chart.yaml
