jenkinsci/helm-charts

.github/stale.yml
https://github.com/apps/stale
Config is taken from https://github.com/helm/charts/blob/92be1ddfc5a242eacae8c34a4401eb1561240d74/.github/stale.yml
=> Add configuration for Stale GitHub app

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/templates/config.yaml, charts/jenkins/templates/jenkins-master-deployment.yaml
Closes #19
Signed-off-by: Torsten Walter <mail@torstenwalter.de>
=> only mount jenkins-secrets if needed

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/values.yaml
Signed-off-by: Vivian Noronha <vivian.noronha@syncier.com>
=> update k8s sidecar image to 0.1.193

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
=> add issue and pull request templates

.github/workflows/sync-readme.yaml, README.md
- updated README to use absolute URLs
- add workflow to sync README.md on changes to gh-pages branch
Idea and code taken from https://github.com/prometheus-community/helm-charts/pull/41
=> Sync README to gh-pages

.github/CODEOWNERS, PROCESSES.md
This allows us to require code review by CODEOWNERS.
Which makes it easier if other charts are alos hosted in this repository.
In the meantime it will just assign us as reviewers to PRs.
- fixes #50
=> add CODEOWNERS

artifacthub-repo.yml
Added the repo admins for artifacthub.io
- fixes #51
=> Add metadatada file for artifacthub.io

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/templates/jenkins-master-deployment.yaml
=> Target port taken from values.yaml

.github/workflows/lint-test.yaml, charts/jenkins/Chart.yaml, charts/jenkins/tests/deployment_test.yaml, charts/jenkins/values.yaml
This PR experiments with [helm unittest](https://github.com/quintush/helm-unittest).
It uses a custom chart-testing image which allows to execute those tests.
To demonstrate that it's working and as initial starting point it adds unit tests for the deployment. Those tests are far from covering everything. But I think it's useful to merge it so that others can also contribute in writing more tests.
Ideally we could add more unit tests for functionality which will be kept for v3.0.0. Then we could use those test to verify if we don't break anything while removing things and getting rid of deprecated terminology.
The change in value file just adds documentation for something which was used already in the template.
=> Add helm unittests

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/templates/jenkins-master-deployment.yaml, charts/jenkins/tests/deployment_test.yaml
- fixes #25
Here unit tests helped to test drive this.
=> Fix indentation of JAVA_OPTS

.github/workflows/lint-test.yaml, ct.yaml
It fixes the failing unit tests on the jenkins-3-0-0 branch. The issue there is that it needs the `--helm3` flag to be passed to helm unittest.
I created two PRs to make this work upstream https://github.com/helm/chart-testing/pull/283 and https://github.com/helm/chart-testing-action/pull/54. I'll update this to use official images once those are merged and also take care of backporting this to the `main` branch.
For now this just fixes the unit tests and enables writing additional ones.
- also build branches on push events
- install plugin locally and mount it into ct container
- use additional-commands to support helm3 for unittests
It requires `--helm3` flag
- fixes …
=> Fix unit tests for helm 3

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/VALUES_SUMMARY.md, charts/jenkins/templates/jenkins-master-alerting-rules.yaml, charts/jenkins/values.yaml
Signed-off-by: Prabhu Jayakumar <j.prabhu91@gmail.com>
It makes namespace of PrometheusRule configurable.
- fixes #43
=> Make namespace of PrometheusRule configurable 

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/templates/jenkins-backup-cronjob.yaml, charts/jenkins/values.yaml
Make activeDeadlineSeconds for backup job configurable 
- fixes #66
=> Make activeDeadlineSeconds for backup job configurable

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/README.md
=> Proofreading and linting on chart readme

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/VALUES_SUMMARY.md, charts/jenkins/templates/_helpers.tpl, charts/jenkins/tests/jcasc-config-test.yaml, charts/jenkins/values.yaml
Allows configuration to use websockets in the default CasC configuration
- fixes #75
=> #75 Add support for enabling websockets via values

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/templates/jenkins-backup-cronjob.yaml
Signed-off-by: Manuel Morejon <manuel@mmorejon.io>
Add nodeSelector section for the backup pod 
Fix tolerations section for the backup pod
=> Backups scheduling

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/VALUES_SUMMARY.md, charts/jenkins/templates/_helpers.tpl, charts/jenkins/templates/deprecation.yaml, charts/jenkins/templates/jenkins-agent-svc.yaml, charts/jenkins/templates/jenkins-controller-networkpolicy.yaml, charts/jenkins/templates/jenkins-controller-statefulset.yaml, charts/jenkins/templates/rbac.yaml, charts/jenkins/templates/service-account-agent.yaml, charts/jenkins/tests/jcasc-config-test.yaml, charts/jenkins/tests/jenkins-agent-svc-test.yaml, charts/jenkins/tests/jenkins-controller-networkpolicy-test.yaml, charts/jenkins/tests/jenkins-controller-statefulset-test.yaml, charts/jenkins/tests/rbac-test.yaml, charts/jenkins/tests/service-account-agent-test.yaml, charts/jenkins/values.yaml
Replaces deprecated terminology "slave" with "agent"
- Closes: #11
=> Rename slave to agent

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/values.yaml
Signed-off-by: Manuel Morejon <manuel@mmorejon.io>
Fix `priorityClassName` entry in the `values.yaml` file
=> Fix priorityClassName default value

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/README.md
This PR adds some documentation for the configuration of ingress and the jenkins url
- fixes #31
=> #31 Add documentation for configuration of the external url and ingress

charts/jenkins/CHANGELOG.md, charts/jenkins/templates/NOTES.txt, charts/jenkins/templates/_helpers.tpl, charts/jenkins/templates/jenkins-controller-statefulset.yaml, charts/jenkins/templates/tests/jenkins-test.yaml
Both flags have been deprecated for a while and have documented alternatives so it's time to get rid of those.
- fixes #
=> Deprecate master.imageTag and slave.imageTag

charts/jenkins/CHANGELOG.md, charts/jenkins/VALUES_SUMMARY.md, charts/jenkins/templates/_helpers.tpl, charts/jenkins/templates/deprecation.yaml, charts/jenkins/templates/jenkins-controller-statefulset.yaml, charts/jenkins/tests/jcasc-config-test.yaml, charts/jenkins/values.yaml
move remaining values used to configure the kubernetes plugin under `agent`
additional changes to https://github.com/jenkinsci/helm-charts/pull/97
- fixes #
=> move kubernetes plugin configuration under agent

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/README.md, charts/jenkins/templates/_helpers.tpl
Signed-off-by: Fabrice Rabaute <fabrice@arista.com>
- [x ] [DCO](https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
=> Enable scriptApproval for JCasC config

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/templates/config.yaml, charts/jenkins/tests/config-test.yaml, charts/jenkins/tests/jenkins-master-deployment-test.yaml, charts/jenkins/values.yaml
Jenkins war file is located in `/usr/share/jenkins/jenkins.war` and can be configured via `master.jenkinsWar`.
- fixes #128
=> Fix location of jenkins.war file.

.github/workflows/release.yaml, CONTRIBUTING.md, charts/jenkins/CHANGELOG.md, charts/jenkins/README.md, charts/jenkins/Tiltfile, charts/jenkins/templates/_helpers.tpl, charts/jenkins/templates/config.yaml, charts/jenkins/templates/jenkins-controller-ingress.yaml, charts/jenkins/templates/jenkins-controller-statefulset.yaml, charts/jenkins/tests/config-test.yaml, charts/jenkins/tests/jenkins-controller-ingress-test.yaml, charts/jenkins/tests/jenkins-controller-statefulset-test.yaml, charts/jenkins/values.yaml
I just created this as PR so that it can be reviewed and ci pipeline runs to check it.
=> Merge changes from main into jenkins-3-0-0

.github/workflows/lint-test.yaml
https://github.com/helm/chart-testing-action/releases/tag/v2.0.0 is releases. It provides native support to run additional commands as it installs `ct` binary locally. 
With this we switch back to an "officially" maintained GitHub action.
- fixes #
=> CI: Use chart-testing-action 2.0.0

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/README.md, charts/jenkins/templates/NOTES.txt, charts/jenkins/values.yaml
- explain how to build and use a custom image
- render message in `NOTES.txt` if default image is used or plugins are installed anyhow
- smaller fixes
- move `httpsKeyStore` further down in values.yaml - I think it's less important for most users.
- fixes #12
=> Recommend installing plugins in custom image

.github/workflows/lint-test.yaml, charts/jenkins/templates/jenkins-controller-statefulset.yaml, charts/jenkins/tests/jenkins-controller-statefulset-test.yaml, charts/jenkins/values.yaml
simplify configuration of probes by moving them to values.yaml
- fixes #
=> move probes to values.yaml

charts/jenkins/README.md
It explains how to use prometheus metrics.
- closes #78
=> Adding Prometheus metrics guidance to readme

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/README.md, charts/jenkins/templates/config.yaml, charts/jenkins/tests/config-test.yaml, charts/jenkins/tests/jcasc-config-test.yaml, charts/jenkins/tests/jenkins-controller-statefulset-test.yaml, charts/jenkins/values.yaml
Merge latest changes from main into jenkins-3-0-0
- fixes #
=> Applying #147 for Jenkins 3.0.0

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/templates/jenkins-controller-statefulset.yaml, charts/jenkins/tests/jenkins-controller-statefulset-test.yaml
Adds Security Context runAsNonRoot to the statefulset
- fixes #
=> add security context runAsNonRoot option

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/README.md
Signed-off-by: Jordan Sokolic <oofnik@gmail.com>
Document how to mount and reference additional secrets for controller config.
#167, #168
requested by @torstenwalter 
- [x ] [DCO](https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x ] Chart Version bumped
- [x ] CHANGELOG.md was updated
=> document extra secrets for IdP usecase

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/README.md
Addresses typo in documentation (#181)
=> address typo in docs

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/templates/jenkins-controller-ingress.yaml, charts/jenkins/templates/jenkins-controller-secondary-ingress.yaml, charts/jenkins/tests/jenkins-controller-ingress-1.19-test.yaml, charts/jenkins/tests/jenkins-controller-secondary-ingress-1.19-test.yaml
=> fix: structure of serviceName/Port has changed in v1 ingress

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/README.md, charts/jenkins/VALUES_SUMMARY.md, charts/jenkins/templates/_helpers.tpl, charts/jenkins/values.yaml
Signed-off-by: guycarmy <guycarmy@gmail.com>
This PR allows changing the maxRequestsPerHostStr in order to deal with higher load of agents running non-JNLP containers.
more info [here](https://support.cloudbees.com/hc/en-us/articles/360054642231-Considerations-for-Kubernetes-Clients-Connections-when-using-Kubernetes-Plugin)
I wouldnt say it "fixes" but its relevant in the situation of [JENKINS-56939](https://issues.jenkins.io/browse/JENKINS-56939) (which is already considered resolved but still happened to me until increasing this setting).
=> Enable setting maxRequestsPerHostStr

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/templates/config-initScripts.yaml, charts/jenkins/templates/config.yaml, charts/jenkins/templates/jenkins-controller-statefulset.yaml
Mount controller initScripts from ConfigMap
- fixes #229
=> Mount init scripts

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/templates/jenkins-controller-statefulset.yaml
=> fix missing newline for httpsKeyStore

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/templates/config-init-scripts.yaml, charts/jenkins/templates/jenkins-controller-statefulset.yaml
=> Fix init scripts ConfigMap name

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/VALUES_SUMMARY.md, charts/jenkins/tests/config-test.yaml, charts/jenkins/tests/jenkins-controller-statefulset-test.yaml, charts/jenkins/values.yaml
Upgrade CasC plugin to 1.47 (as it fails with newer Credentials Plugin versions). \
While I was there, upgraded kubernetes plugin too.
- fixes #247
=> Update casc plugin

.github/workflows/sync-lts.yaml, charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml
Automates the updating of the Jenkins LTS version so this doesn't have to be done manually anymore.
Fixes #259
=> feat: add GHA to update to the latest LTS

.github/workflows/sync-lts.yaml
Minor fix to correct the templating of the generated PR title for automatic lts updates.
=> fix: corrected templating PR title for LTS update

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/VALUES_SUMMARY.md
Describes `controller.jenkinsUrl` option in `VALUES_SUMMARY.md` otherwise it gets lost in `README.md`.
=> Add controller.jenkinsUrl to VALUES_SUMMARY.md

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/VALUES_SUMMARY.md, charts/jenkins/ci/other-values.yaml, charts/jenkins/tests/config-test.yaml, charts/jenkins/tests/jenkins-controller-statefulset-test.yaml, charts/jenkins/values.yaml
Upgrade jenkins to 2.277.1
Refer - https://www.jenkins.io/changelog-stable
=> chore(deps): bump jenkins to 2.277.1

.github/workflows/sync-lts.yaml
=> Use github app token for syncing LTS

charts/jenkins/Chart.yaml, charts/jenkins/templates/_helpers.tpl, charts/jenkins/templates/jenkins-controller-statefulset.yaml, charts/jenkins/templates/secret-additional.yaml, charts/jenkins/tests/jcasc-config-test.yaml, charts/jenkins/tests/secret-additional-test.yaml, charts/jenkins/values.yaml
Signed-off-by: Ricardo Rosales <missingcharacter@gmail.com>
Removes `if` checking for `.Values.agent.command`, if the `command` is not set causes plus if a user goes to kubernetes cloud page and hits `save` or `apply` causes the `sleep` command to be set, see these lines: https://github.com/jenkinsci/kubernetes-plugin/blob/16946b9fa1d3b6bd212417268b52a5319b4dca77/src/main/resources/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate/config.jelly#L25-L27
Creates kubernetes secrets and mounts them according to https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/secrets.adoc#kubernetes-secrets
- fixes …
=> Additional secrets are created in kubernetes and mounted on the controller

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/README.md, charts/jenkins/VALUES_SUMMARY.md, charts/jenkins/tests/jenkins-controller-statefulset-test.yaml, charts/jenkins/tests/secret-additional-test.yaml
- I'm documenting `controller.additionalSecrets` in `VALUES_SUMMARY.md`
- I'm updating the `#### Additional Secrets` Example with a simpler one using `controller.additionalSecrets`
- I'm adding `controller.additionalSecrets` tests to `jenkins-controller-statefulset-test.yaml`
- fixes https://github.com/jenkinsci/helm-charts/issues/167
=> Document controller.additionalSecrets in VALUES_SUMMARY.md

.github/workflows/sync-lts.yaml
Otherwise it just sets the author as the last person to commit to the repo
=> Set committer and author for automatic lts PRs

charts/jenkins/Chart.yaml, charts/jenkins/templates/jenkins-controller-statefulset.yaml, charts/jenkins/tests/jenkins-controller-statefulset-test.yaml
Signed-off-by: Joseph, Abhilash  <abhilash.joseph@resideo.com>
Updates the template generation for environment using tpl function around the environment variables.
https://github.com/jenkinsci/helm-charts/issues/324
*(optional, in `fixes 324(, fixes #324 , ...)` format, will close that issue when PR gets merged)*
- fixes #324
=> Use tpl function for environment vars

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/VALUES_SUMMARY.md, charts/jenkins/ci/other-values.yaml, charts/jenkins/tests/config-test.yaml, charts/jenkins/tests/jenkins-controller-statefulset-test.yaml, charts/jenkins/values.yaml
Update Git plugin version to v4.7.1
Update ldap plugin version to v2.5
=> chore(deps): Upgrade plugins - git and ldap

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/templates/jenkins-controller-ingress.yaml
Signed-off-by: ymian <gopher.mian@outlook.com>
fix controller-ingress line feed bug
=> fix controller-ingress line feed bug

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/VALUES_SUMMARY.md
Related PR: #362
Signed-off-by: donhui <977675308@qq.com>
- fixes #
=> Correct docs on disabling plugin installation

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/tests/jenkins-controller-statefulset-test.yaml, charts/jenkins/values.yaml
This updates kiwigrid sidecar to the latest version.
> Fixed some CVEs by upgrading dependencies
> https://github.com/kiwigrid/k8s-sidecar/releases/tag/1.12.2
- fixes #
=> update kiwigrid sidecar

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/templates/_helpers.tpl, charts/jenkins/unittests/jcasc-config-test.yaml, charts/jenkins/values.yaml
This allows setting nodeUsageMode via values file.
- fixes #344
=> allow configuration of nodeUsageMode

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/templates/_helpers.tpl, charts/jenkins/templates/home-pvc.yaml, charts/jenkins/templates/jenkins-agent-svc.yaml, charts/jenkins/templates/jenkins-backup-cronjob.yaml, charts/jenkins/templates/jenkins-backup-rbac.yaml, charts/jenkins/templates/jenkins-controller-alerting-rules.yaml, charts/jenkins/templates/jenkins-controller-backendconfig.yaml, charts/jenkins/templates/jenkins-controller-ingress.yaml, charts/jenkins/templates/jenkins-controller-networkpolicy.yaml, charts/jenkins/templates/jenkins-controller-route.yaml, charts/jenkins/templates/jenkins-controller-secondary-ingress.yaml, charts/jenkins/templates/jenkins-controller-servicemonitor.yaml, charts/jenkins/templates/jenkins-controller-statefulset.yaml, charts/jenkins/templates/jenkins-controller-svc.yaml, charts/jenkins/templates/rbac.yaml, charts/jenkins/templates/secret-additional.yaml, charts/jenkins/templates/secret-https-jks.yaml, charts/jenkins/templates/secret.yaml, charts/jenkins/templates/service-account-agent.yaml, charts/jenkins/templates/service-account.yaml
When the Chart Version has  a + in it to identify Build number the current version breaks.
this updates the labels to use a sanitized version of the label
- fixes #
- [ X] [DCO](https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ X] Chart Version bumped
- [X ] CHANGELOG.md was updated
=> sanitizing the jenkins labels

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/README.md
This adds new documentation for backing up and restoring Jenkins installation on PVC.
- fixes #
=> New Backup and Restore Documentation

.github/workflows/lint-test.yaml
Signed-off-by: Tim Jacomb timjacomb1+github@gmail.com
- fixes #
=> Update versions we test against

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/templates/jenkins-controller-networkpolicy.yaml, charts/jenkins/unittests/jenkins-controller-networkpolicy-test.yaml
Closes https://github.com/jenkinsci/helm-charts/issues/463
Signed-off-by: Dominykas Blyžė <hello@dominykas.com>
- fixes #463 
---
I wasn't sure about updating Chart Version / CHANGELOG - there's an outstanding PR, which already includes the next patch version? Happy to make whatever changes are necessary!
=> Disallow ingress on port 50000 when agent listener is disabled

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/templates/jenkins-controller-statefulset.yaml
- fixes #364 
@maorfr @torstenwalter @mogaal @wmcdona89 @timja 
I don't have an environment to easily run Helm tests right now, otherwise I would have written one. :)
=> Fix mounting of https keystore secret when httpsKeyStore is enabled

.github/workflows/sync-lts.yaml, charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/VALUES_SUMMARY.md, charts/jenkins/ci/other-values.yaml, charts/jenkins/templates/jenkins-controller-statefulset.yaml, charts/jenkins/unittests/jenkins-controller-statefulset-test.yaml, charts/jenkins/values.yaml
Signed-off-by: Igor Nikonorov <igor.nikonorov@syncier.com>
- fixes #
=> Add containerSecurityContext

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/unittests/__snapshot__/jenkins-controller-statefulset-test.yaml.snap, charts/jenkins/unittests/config-test.yaml, charts/jenkins/unittests/jenkins-controller-statefulset-test.yaml, charts/jenkins/values.yaml
- Replaces #512
I could not add a commit to that branch so I needed to push to my repo to be able to create a PR.
=> chore(deps): bump lts to 2.319.1 and bump plugins

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/README.md
Adds a necessary environment variable to the README, to make proxy settings work for `jenkins-plugin-cli` to work
- fixes #
=> Add JAVA_OPTIONS so proxy settings get picked by jenkins-plugin-cli

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/unittests/__snapshot__/jenkins-controller-statefulset-test.yaml.snap, charts/jenkins/unittests/config-test.yaml, charts/jenkins/unittests/jenkins-controller-statefulset-test.yaml, charts/jenkins/values.yaml
=> Update plugin versions

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/VALUES_SUMMARY.md
=> Fix docs for installLatestPlugins

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/unittests/__snapshot__/jenkins-controller-statefulset-test.yaml.snap, charts/jenkins/unittests/config-test.yaml, charts/jenkins/unittests/jenkins-controller-statefulset-test.yaml, charts/jenkins/values.yaml
=> update configuration-as-code plugin to 1.55.1

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/VALUES_SUMMARY.md, charts/jenkins/unittests/jcasc-config-test.yaml, charts/jenkins/unittests/jenkins-controller-statefulset-test.yaml, charts/jenkins/values.yaml
Update kiwigrid/k8s-sidecar:1.15.0
Update jenkins/inbound-agent:4.11.2-4
- fixes #
=> Update kiwigrid and inbound-agent images

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/templates/jenkins-backup-rbac.yaml
Signed-off-by: Curt Cunning <curt.cunning@outlook.com>
This PR replaces the name of the Role created for the Backup ServiceAccount and has it match the value used in the Backup RoleBinding.
- fixes #571
The Role was updated instead of the RoleBinding as the RoleRef is immutable and would require recreating the RoleBinding resource instead of updating it in place with a helm upgrade.
=> Update Role name to match RoleBinding

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/VALUES_SUMMARY.md, charts/jenkins/templates/jenkins-agent-svc.yaml, charts/jenkins/unittests/jenkins-agent-svc-test.yaml, charts/jenkins/values.yaml
Signed-off-by: Khachatur Ashotyan <ping@lanycrost.net>
- fixes #589
=> externalTrafficPolicy and loadBalancerSourceRanges for agent Listener service

.github/workflows/lint-test.yaml, .github/workflows/release.yaml, CONTRIBUTING.md, charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/unittests/jcasc-config-test.yaml
- Updates tests for latest helm. Is this a breaking change?
=> Bump Helm (3.4.0 -> 3.8.2) and helm-unittest (0.2.6 -> 0.2.8)

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/templates/jenkins-controller-statefulset.yaml
Prior to this change, when using both controller.initConfigMap and controller.initScripts k8s failed to mount the projected volumes.
This change adds the missing 'sources' key definition for projected volume configuration.
Signed-off-by: Carlos Garcia <carlos.garcia@kindredgroup.com>
- fixes #
=> Fix projected volumes definition.

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/unittests/__snapshot__/jenkins-controller-statefulset-test.yaml.snap, charts/jenkins/unittests/config-test.yaml, charts/jenkins/unittests/jenkins-controller-statefulset-test.yaml, charts/jenkins/values.yaml
Update plugins, especially the Git one.
- fixes #642
Used last plugins versions specified in [Docker Jenkins LTS infra image](https://github.com/jenkins-infra/docker-jenkins-lts/blob/main/plugins.txt)
=> chore: update plugins

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/README.md
The variable expected by jvm is prefixed by underscore.
- fixes #528
=> Fix name of Java options environement variable

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/README.md
Signed-off-by: Yuneui Jeong <uniglot@gmail.com>
Update README to note the existence of a required environmental variable `AWS_REGION` in case of using an AWS S3 bucket as the backup store. 
If someone wants to use an S3 bucket that is in a region other than `eu-central-1`, it will complain like: `BucketRegionError: incorrect region, the bucket is not in 'eu-central-1' region at endpoint ''`.
- fixes #631 
If I need to change something, please let me know.
=> Update README about AWS_REGION env variable

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/VALUES_SUMMARY.md, charts/jenkins/templates/_helpers.tpl, charts/jenkins/unittests/jcasc-config-test.yaml, charts/jenkins/values.yaml
Signed-off-by: Miles Wilson <wilson.mil@icloud.com>
- fixes #684
=> Added security spec to jcasc values

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/unittests/__snapshot__/jenkins-controller-statefulset-test.yaml.snap, charts/jenkins/unittests/config-test.yaml, charts/jenkins/unittests/jenkins-controller-statefulset-test.yaml, charts/jenkins/values.yaml
Fixing plugin version matrix to some default installs
fixes #704, will close that issue when PR gets merged
=> Update default plugin installation versions

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/templates/jenkins-controller-statefulset.yaml
`scheduling.k8s.io/v1beta1` has been [dropped](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#priorityclass-v122) in K8S 1.22, if k8s does not support priority class, it will raise error, it should be user who decide whether or not to use priority class.
- fixes #
=> delete restriction when setting priority

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/VALUES_SUMMARY.md, charts/jenkins/templates/_helpers.tpl, charts/jenkins/values.yaml
Kubernetes plugin support the host-network option from UI. This option is missing in Chart.
=> Add hostNetworking option for agents

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/templates/config.yaml
Signed-off-by: ShihouinYoruichi <sms13242000@gmail.com>
This fix would allow the users to safely disable the sidecar's configAutoReload feature in their first deployment with the chart, which still preserves the ability to apply the default JCasC setting values as the sample guidelines for them. In addition, if they do not even want to have those default configuration, which is not highly recommended, they can set the Helm value flag controller.JCasC.defaultConfig to false.
- fixes #618 
@timja @maorfr @torstenwalter @mogaal @wmcdona89
=> Improve configAutoReload related condition

.github/workflows/lint-test.yaml, .github/workflows/sync-lts.yaml
Signed-off-by: Alexander Brandes <brandes.alexander@web.de>
https://github.com/jenkins-infra/helpdesk/issues/3176
=> Address `set-output` deprecation

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/templates/jenkins-controller-statefulset.yaml, charts/jenkins/unittests/secret-existing-test.yaml
Signed-off-by: SylivanKenobi <sypsilon@hotmail.com>
It enables the use of dynamically created Secrets with this Chart.
- fixes #716
=> use template for additionalExistingSecrets

.github/workflows/lint-test.yaml
Should hopefully unblock https://github.com/jenkinsci/helm-charts/pull/760
I don't have much time to spend on this so I may not be able to debug any failures if this doesn't help
=> Test against supported versions of k8s

.github/workflows/lint-test.yaml, charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/templates/NOTES.txt
None, I noticed the issue and fixed it directly.
=> Fix Jenkins URL rendering in chart notes

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/templates/_helpers.tpl, charts/jenkins/unittests/jcasc-config-test.yaml, charts/jenkins/values.yaml
Signed-off-by: Marc Liechti <marc.liechti@trivo.ch>
* Add the possibility to define `secretEnvVars` as documented in the CasC docs: 
* https://www.jenkins.io/doc/pipeline/steps/kubernetes/
=> Add possibility to specify secretEnvVars

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/VALUES_SUMMARY.md, charts/jenkins/templates/jenkins-backup-cronjob.yaml, charts/jenkins/values.yaml
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md
Signed-off-by: Mohsen <mohsen0@users.noreply.github.com>
=> Deprecating CronJob batch/v1beta1 to batch/v1

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/unittests/service-account-agent-test.yaml, charts/jenkins/unittests/service-account-test.yaml
Signed-off-by: Tim Jacomb <timjacomb1@gmail.com>
Removes hardcoding of chart version in tests to make maintenance easier
https://github.com/jenkinsci/helm-charts/pull/799#issuecomment-1443803222
https://github.com/jenkinsci/helm-charts/pull/799#issuecomment-1443803222
=> Don't hardcode version in tests

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/templates/_helpers.tpl, charts/jenkins/unittests/jcasc-config-test.yaml
This enables directConnection for agents to allow agents to be configured to connect direct to the JNLP port on the
controller, preventing the need for an external HTTP endpoint.
=> Agent direct connection

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/README.md, charts/jenkins/unittests/jcasc-config-test.yaml, charts/jenkins/values.yaml
- Document directConnection in README
- Add default value for directConnection to `values.yaml`
Follow up to #816 
@timja
=> Direct connection docs and default value

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/values.yaml
I fixed a small grammatical typo in a comment for clarity
Signed-off-by: Jacob Olson <olsonjac17@gmail.com>
- fixes #
=> Update wording in values.yaml

.github/workflows/lint-test.yaml, charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/ci/other-values.yaml, charts/jenkins/unittests/__snapshot__/jenkins-controller-statefulset-test.yaml.snap, charts/jenkins/unittests/config-test.yaml, charts/jenkins/unittests/jenkins-controller-statefulset-test.yaml, charts/jenkins/values.yaml
Additionally, I added links to the plugin page if you want to check out the release notes or source code.
=> Update various bundled plugins

.github/ISSUE_TEMPLATE/config.yml, CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/README.md
Typo fixes are covered by https://github.com/jenkinsci/helm-charts/pull/843
=> Enhance appearance on artifacthub

README.md
Small rewording of the README title to reflect what these helm charts are about.
I dropped the license disclaimer too, it's enough if we have it on one occasion.
=> Revise README title

.github/workflows/lint-test.yaml, .github/workflows/release.yaml
Keeps the individual noise a bit down.
=> Pin GH actions (where applicable)

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/VALUES_SUMMARY.md, charts/jenkins/unittests/jcasc-config-test.yaml, charts/jenkins/unittests/jenkins-controller-statefulset-test.yaml, charts/jenkins/values.yaml
=> Update sidecars and inbound agent

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/unittests/jenkins-controller-statefulset-test.yaml
This test case should match the LTS version we ship, instead of an ancient release from 2020.
```[tasklist]
```
=> Update controller image in tests

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/README.md
There are now 1918 plugins in https://plugins.jenkins.io/, so change "hundreds" to "thousands" to reflect the actual number.
=> docs: update word from hundreds to over 1800 to align with blurb

.github/workflows/release.yaml, charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml
This PR fixes the chart release by using `strenv` to properly add Artifact Hub annotation to Chart.yaml.
Fixup of:
- #949
```[tasklist]
```
Tested on a fork:
- Release https://github.com/lemeurherve/jenkinsci-helm-charts/releases/tag/jenkins-9.0.0
- GHA logs: https://github.com/lemeurherve/jenkinsci-helm-charts/actions/runs/6968817556/job/18963479732
- <details><summary>Resulting Chart.yaml:</summary>
```
apiVersion: v2
name: jenkins
home: https://jenkins.io/
version: 9.0.0
appVersion: 2.426.1
description: Jenkins - Build great things at any scale! The leading open source automation server, Jenkins provides over 1800 plugins to support building, deploying and automating any project.
sources:
- …
```
=> fixup: use `strenv` to properly add Artifact Hub annotation

.github/PULL_REQUEST_TEMPLATE.md
=> Fix typo in PR template checkboxes

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/VALUES_SUMMARY.md, charts/jenkins/values.yaml
Fixes the docs for `controller.initScripts`.
- Fixes #
```[tasklist]
```
=> docs: Fixed docs for controller.initScripts

.github/renovate-config.json5, .github/workflows/lint-test.yaml, .github/workflows/linter.yml, .github/workflows/release.yaml, .github/workflows/renovate.yaml, .github/workflows/sync-readme.yaml, .gitleaksignore, charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/README.md
Updates super-linter to v6
- Fixes #
```[tasklist]
```
I bumped the Chart version so that it can be merged after #995
=> Super linter bump

.github/renovate-config.json5
Added a configuration to wait 12 hours before creating a PR for new releases
- Fixes #
```[tasklist]
```
I also configured the hourly limit, increasing it to 5 from the normal 2.
=> chore(Renovate): Wait for a release to reach a minimum age

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml
Fixes the entries in the changelog, mistakenly entered by the Renovate setup.
- Fixes #1021 
```[tasklist]
```
Sorry for that! It's on my todo-list to check and see why this is broken all of the sudden.
=> chore: Fix changelog entries

.github/renovate-entrypoint.sh, .github/workflows/linter.yml
Fixes the Renovate comment to auto-update norwoodj/helm-docs
- Fixes #
```[tasklist]
```
=> chore: Fix Renovate comment for helm-docs

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/README.md
Closes https://github.com/jenkinsci/helm-charts/pull/963, because I cannot check the PR out locally.
```[tasklist]
```
=> Fix Prometheus controller in docs

.github/PULL_REQUEST_TEMPLATE.md, .github/helm-docs.sh
The change proposed checks that `helm-docs` is available, and if not, notifies the user to install it:
```[tasklist]
```
=> Check if 'helm-docs' is available

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/Tiltfile
=> Fix deprecated value reference in Tiltfile

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/VALUES.md, charts/jenkins/templates/_helpers.tpl, charts/jenkins/templates/auto-reload-config.yaml, charts/jenkins/templates/jenkins-controller-statefulset.yaml, charts/jenkins/unittests/__snapshot__/jenkins-controller-statefulset-test.yaml.snap, charts/jenkins/unittests/jenkins-controller-statefulset-test.yaml, charts/jenkins/values.yaml
- Fixes #1139
```[tasklist]
```
=> Add additional mountPaths and logging file paths for config reload container

.github/workflows/release.yaml
=> Add another place for renovate to update helm

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/README.md
Add doc for OCI installation
Add doc for OCI installation
- Fixes
Fully fix https://github.com/jenkinsci/helm-charts/issues/1180 by providing documentation
```[tasklist]
```
=> Add doc for OCI installation

charts/jenkins/Chart.yaml, charts/jenkins/README.md
It was pointing to a non-existent file
=> Fix link to VALUES.md in the chart's README

.github/renovate-config.json5
Fixes my mistake from #1285 (somehow missed this after copying from my IDE (which removes those slashes on copy))
- Fixes #
```[tasklist]
```
Sorry about that!
=> fix: add missing backslashes

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/README.md
As the title says :)
- Fixes #
```[tasklist]
```
=> Update plugin count

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/values.yaml
- Fix indentation because otherwise yaml formater treats comments as a key
```[tasklist]
- done I bumped the "version" key in `./charts/jenkins/Chart.yaml`.
- done I added a new changelog entry to `./charts/jenkins/CHANGELOG.md`.
- done I followed the [technical requirements](https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#technical-requirements).
- done I ran `.github/helm-docs.sh` from the project root.
```
=> fix: Fix indenation in values.yaml

.github/workflows/lint-test.yaml
Updated the ci scripts to use the currently supported releases
- Fixes #
```[tasklist]
```
Requires updating required status checks
=> ci: update kindest/node versions to currently supported releases

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/templates/_helpers.tpl, charts/jenkins/unittests/__snapshot__/garbage-collect-test.yaml.snap, charts/jenkins/unittests/garbage-collect-test.yaml
- Fixes #1351
```[tasklist]
```
=> fix: Added garbage collection to secondary clouds (#1351)

.github/renovate-config.json5
see https://github.com/renovatebot/renovate/releases/tag/40.0.0
- Fixes #
```[tasklist]
```
=> Tweak allowed post upgrade commands

charts/jenkins/CHANGELOG.md, charts/jenkins/Chart.yaml, charts/jenkins/VALUES.md, charts/jenkins/templates/_helpers.tpl, charts/jenkins/unittests/__snapshot__/garbage-collect-test.yaml.snap, charts/jenkins/unittests/__snapshot__/instance-cap-test.yaml.snap, charts/jenkins/unittests/__snapshot__/jcasc-config-test.yaml.snap, charts/jenkins/values.yaml
Signed-off-by: AvivGuiser <avivguiser@gmail.com>
add options to specify the registry for the jenkins agent image
fixes #1349
- Fixes #
```[tasklist]
```
=> feat: add options to specify agent image registry

.github/renovate-entrypoint.sh
=> Ensure renovate script exits on failure

.github/renovate-config.json5
=> Migrate renovate config item
